In [4]:
import pandas as pd

In [5]:
import os

# Cost Report Cleaning

In [6]:
costReport_2015 = pd.read_csv(r"/Users/brandonnguyen/Desktop/ACE_Project/2015_CostReport.csv")

/var/folders/7t/7qf1whc969jcpbccjdpbv57r0000gn/T/ipykernel_4460/3944741479.py:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  costReport_2015 = pd.read_csv(r"/Users/brandonnguyen/Desktop/ACE_Project/2015_CostReport.csv")

In [7]:
costReport_2015

,rpt_rec_num,provider_ccn,facility_name,street_address,city,state_code,zip_code,county,medicare_cbsa_number,rural_versus_urban,...,total_salaries_from_worksheet_a,total_salaries_adjusted,total_current_assets,total_current_liabilities,total_fixed_assets,total_fund_balances,total_liabilities,total_other_assets,wage_related_costs_core,fixed_equipment
0,1089712,495134,RIDGECREST MANOR NURSING & REHAB CTR,157 ROSS-CARTER BLVD,DUFFIELD,VA,24244,SCOTT,28700.0,U,...,660232.0,660232.0,1439227.0,453591.0,55061.0,311430.0,453590.0,-729268.0,80664.0,NaN
1,1091410,75417,REGENCY HEIGHTS OF NORWICH LLC,60 CROUCH AVENUE,NORWICH,CT,6360,NEW LONDON,35980.0,U,...,1118860.0,1118860.0,980150.0,2765768.0,671306.0,-4896947.0,6584403.0,36000.0,559430.0,NaN
2,1093283,165252,WESTVIEW ACRES CARE CENTER,203 SW LORRAINE,LEON,IA,50144,DECATUR,99916.0,R,...,348614.0,348614.0,244239.0,192098.0,NaN,52141.0,192098.0,NaN,42209.0,NaN
3,1095547,225497,VERO HEALTH & REHAB PARKWAY,1190 VFW PARKWAY,WEST ROXBURY,MA,2132,SUFFOLK,14454.0,U,...,601118.0,601118.0,1728824.0,1824376.0,26949.0,6382.0,1824376.0,74985.0,113676.0,NaN
4,1095966,265161,WILSONS CREEK NURSING & REHAB,3403 WEST MT VERNON,SPRINGFIELD,MO,65802,GREENE,44180.0,U,...,363088.0,363088.0,807209.0,808822.0,NaN,-1613.0,808822.0,NaN,99778.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15397,1310508,555352,R FELLEN INC,2939 SOUTH PEACH AVE,FRESNO,CA,93725,FRESNO,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15398,1317431,45357,PULASKI OPERATIONS LLC PREMIER HEAL,3600 RICHARDS RD.,NORTH LITTLE ROCK,AR,72117,PULASKI,38220,U,...,3486025.0,3486025.0,7434052.0,9246047.0,349333.0,-1203193.0,9246047.0,259469.0,419924.0,39239.0
15399,1334160,55728,SANTA CLARITA POST-ACUTE CARE CENTER,23801 NEWHALL AVENUE,NEWHALL,CA,91321,LOS ANGELES,31084,U,...,2625866.0,2625866.0,1693175.0,1774829.0,12822.0,2543562.0,1774829.0,2612394.0,482355.0,7000.0
15400,1338020,395735,LIFEQUEST NURSING CENTER,2450 JOHN FRIES HIGHWAY,QUAKERTOWN,PA,18951,BUCKS,33874,U,...,3877209.0,3877209.0,8648747.0,3028355.0,1551470.0,97893.0,10102324.0,NaN,667146.0,675326.0
15401,1345592,275122,CREST NURSING HOME,3131 AMHERST AVENUE,BUTTE,MT,59701,SILVERBOW,99927,R,...,1935568.0,1935568.0,1222732.0,340244.0,295546.0,1178034.0,340244.0,NaN,422156.0,NaN

In [8]:
costReport_2015.columns

Index(['rpt_rec_num', 'provider_ccn', 'facility_name', 'street_address',
       'city', 'state_code', 'zip_code', 'county', 'medicare_cbsa_number',
       'rural_versus_urban', 'fiscal_year_begin_date', 'fiscal_year_end_date',
       'type_of_control', 'accounts_receivable', 'accounts_payable',
       'buildings', 'cash_on_hand_and_in_banks', 'general_fund_balance',
       'gross_revenue', 'inpatient_pps_amount', 'inpatient_revenue',
       'less_total_operating_expense', 'less_discounts_on_patients',
       'major_movable_equipment', 'net_income', 'net_income_from_patients',
       'net_patient_revenue', 'number_of_beds', 'other_assets',
       'other_current_liabilities', 'overhead_non_salary_costs',
       'snf_admissions_other', 'snf_admissions_title_xix',
       'snf_admissions_title_xviii', 'snf_admissions_total',
       'snf_average_length_of_stay_tot', 'snf_average_length_stay_xix',
       'snf_average_length_stay_xviii', 'snf_days_other', 'snf_days_title_xix',
       'snf_days_title_xviii', 'snf_days_total', 'snf_discharges_title_other',
       'snf_discharges_title_xix', 'snf_discharges_title_xviii',
       'snf_discharges_total', 'snf_number_of_beds', 'snf_bed_days_available',
       'salaries_wages_and_fees_payable', 'total_assets',
       'total_bed_days_available', 'total_costs', 'total_days_other',
       'total_days_title_xix', 'total_days_title_xviii', 'total_days_total',
       'total_discharges_title_other', 'total_discharges_title_xix',
       'total_discharges_title_xviii', 'total_discharges_total',
       'total_general_inpatient_revenue', 'total_income',
       'total_liab_and_fund_balances', 'total_rug_days',
       'total_salaries_from_worksheet_a', 'total_salaries_adjusted',
       'total_current_assets', 'total_current_liabilities',
       'total_fixed_assets', 'total_fund_balances', 'total_liabilities',
       'total_other_assets', 'wage_related_costs_core', 'fixed_equipment'],
      dtype='object')

In [10]:
filteredCostReport_2015 = costReport_2015[['rpt_rec_num', 'provider_ccn',
       'rural_versus_urban','gross_revenue', 'inpatient_pps_amount', 'inpatient_revenue',
       'net_income', 'net_income_from_patients',
       'net_patient_revenue', 'number_of_beds',
       'total_bed_days_available', 'total_costs','total_income']]

In [11]:
filteredCostReport_2015

,rpt_rec_num,provider_ccn,rural_versus_urban,gross_revenue,inpatient_pps_amount,inpatient_revenue,net_income,net_income_from_patients,net_patient_revenue,number_of_beds,total_bed_days_available,total_costs,total_income
0,1089712,495134,U,1800296.0,154022.0,1800296.0,311430.0,311308.0,1520630.0,120.0,7320.0,211585.0,311431.0
1,1091410,75417,U,2843541.0,393088.0,2843541.0,-588469.0,-588476.0,2416825.0,114.0,8550.0,207903.0,-588469.0
2,1093283,165252,R,613243.0,20234.0,613243.0,-47859.0,-39135.0,600033.0,60.0,5520.0,22920.0,-30743.0
3,1095547,225497,U,1935277.0,172528.0,1935277.0,-63638.0,-66306.0,1378163.0,141.0,8601.0,158386.0,-63638.0
4,1095966,265161,U,818175.0,46270.0,818175.0,-1613.0,-6087.0,769155.0,172.0,5332.0,56556.0,-1613.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15397,1310508,555352,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15398,1317431,45357,U,8371129.0,2329910.0,8371129.0,-67387.0,-69923.0,8707761.0,120.0,43800.0,1336487.0,-67387.0
15399,1334160,55728,U,9132853.0,3038405.0,9132853.0,254508.0,143887.0,7642138.0,99.0,36135.0,1250099.0,254508.0
15400,1338020,395735,U,17262402.0,2409580.0,17262402.0,97893.0,-162366.0,11844641.0,140.0,51240.0,2327325.0,97893.0
15401,1345592,275122,R,4803468.0,784415.0,4803468.0,-206640.0,-208377.0,4168276.0,103.0,37595.0,624773.0,-206640.0

In [12]:
filteredCostReport_2015.to_csv("filteredCostReport_2015.csv", index=False)

In [13]:
filteredCostReport_2015

,rpt_rec_num,provider_ccn,rural_versus_urban,gross_revenue,inpatient_pps_amount,inpatient_revenue,net_income,net_income_from_patients,net_patient_revenue,number_of_beds,total_bed_days_available,total_costs,total_income
0,1089712,495134,U,1800296.0,154022.0,1800296.0,311430.0,311308.0,1520630.0,120.0,7320.0,211585.0,311431.0
1,1091410,75417,U,2843541.0,393088.0,2843541.0,-588469.0,-588476.0,2416825.0,114.0,8550.0,207903.0,-588469.0
2,1093283,165252,R,613243.0,20234.0,613243.0,-47859.0,-39135.0,600033.0,60.0,5520.0,22920.0,-30743.0
3,1095547,225497,U,1935277.0,172528.0,1935277.0,-63638.0,-66306.0,1378163.0,141.0,8601.0,158386.0,-63638.0
4,1095966,265161,U,818175.0,46270.0,818175.0,-1613.0,-6087.0,769155.0,172.0,5332.0,56556.0,-1613.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15397,1310508,555352,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15398,1317431,45357,U,8371129.0,2329910.0,8371129.0,-67387.0,-69923.0,8707761.0,120.0,43800.0,1336487.0,-67387.0
15399,1334160,55728,U,9132853.0,3038405.0,9132853.0,254508.0,143887.0,7642138.0,99.0,36135.0,1250099.0,254508.0
15400,1338020,395735,U,17262402.0,2409580.0,17262402.0,97893.0,-162366.0,11844641.0,140.0,51240.0,2327325.0,97893.0
15401,1345592,275122,R,4803468.0,784415.0,4803468.0,-206640.0,-208377.0,4168276.0,103.0,37595.0,624773.0,-206640.0

In [14]:
costReport_2016 = pd.read_csv(r"/Users/brandonnguyen/Desktop/ACE_Project/2016_CostReport.csv")

In [15]:
costReport_2016

,rpt_rec_num,provider_ccn,facility_name,street_address,city,state_code,zip_code,county,medicare_cbsa_number,rural_versus_urban,...,total_salaries_from_worksheet_a,total_salaries_adjusted,total_current_assets,total_current_liabilities,total_fixed_assets,total_fund_balances,total_liabilities,total_other_assets,wage_related_costs_core,fixed_equipment
0,1123428,75061,REGENCY HEIGHTS OF STAMFORD,53 COURTLAND AVE,STAMFORD,CT,6902,WINDHAM,14860.0,U,...,1487845.0,1487845.0,719872.0,-3027.0,439715.0,458455.0,725237.0,24105.0,359699.0,NaN
1,1123429,75185,ANDREW HOUSE,66 CLINIC DRIVE,NEW BRITAIN,CT,6051,HARTFORD,25540.0,U,...,633718.0,633718.0,377888.0,1549368.0,251997.0,-384377.0,1054500.0,40238.0,89852.0,NaN
2,1126697,366429,ZANESVILLE NH LLC,1420 AUTUMN DR.,ZANESVILLE,OH,43701,MUSKINGHAM,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1129197,515021,MADISON PARK HEALTHCARE,700 MADISON AVE,HUNTINGTON,WV,25704-2630,CABELL,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1132719,285295,TABITHA AT WILLIAMSBURG,3355 ORWELL ST,LINCOLN,NE,68516,LANCASTER,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15099,1344461,345343,BRIAN CTR HLTH & REHAB-GOLDSBORO,1700 WAYNE MEMORIAL,GOLDSBORO,NC,27530,WAYNE,24140.0,U,...,4092841.0,4092841.0,1045027.0,2246791.0,17813293.0,8741318.0,10208573.0,91571.0,581654.0,667678.0
15100,1346007,56078,LAKEVIEW TERRACE,831 S. LAKE STREET,LOS ANGELES,CA,90057,LOS ANGELES,31084.0,U,...,3912452.0,3912452.0,2027249.0,2662674.0,NaN,-583460.0,2662674.0,51965.0,1029138.0,NaN
15101,1346320,395582,MOUNTAIN CITY NURSING AND REHABILITA,403 HAZLE TOWNSHIP BLVD,HAZLE TOWNSHIP,PA,18202,LUZERNE,42540.0,U,...,11863241.0,11863241.0,3402017.0,3871406.0,50801.0,423748.0,4117150.0,1088080.0,2466590.0,NaN
15102,1354979,375556,SHERWOOD MANOR NURSING HOME,2416 W. 51ST ST,TULSA,OK,74107,TULSA,46140.0,U,...,1795789.0,1795789.0,406461.0,287886.0,5948.0,-154504.0,566912.0,NaN,205572.0,NaN
15103,1358974,375472,THE WOLFE LIVING CENTER,18501 NE 63RD,HARRAH,OK,73045,OKLAHOMA,36420.0,U,...,1324434.0,1324434.0,433226.0,230419.0,449232.0,652039.0,230419.0,NaN,192746.0,27381.0

In [16]:
costReport_2016.columns

Index(['rpt_rec_num', 'provider_ccn', 'facility_name', 'street_address',
       'city', 'state_code', 'zip_code', 'county', 'medicare_cbsa_number',
       'rural_versus_urban', 'fiscal_year_begin_date', 'fiscal_year_end_date',
       'type_of_control', 'accounts_receivable', 'accounts_payable',
       'buildings', 'cash_on_hand_and_in_banks', 'general_fund_balance',
       'gross_revenue', 'inpatient_pps_amount', 'inpatient_revenue',
       'less_total_operating_expense', 'less_discounts_on_patients',
       'major_movable_equipment', 'net_income', 'net_income_from_patients',
       'net_patient_revenue', 'number_of_beds', 'other_assets',
       'other_current_liabilities', 'overhead_non_salary_costs',
       'snf_admissions_other', 'snf_admissions_title_xix',
       'snf_admissions_title_xviii', 'snf_admissions_total',
       'snf_average_length_of_stay_tot', 'snf_average_length_stay_xix',
       'snf_average_length_stay_xviii', 'snf_days_other', 'snf_days_title_xix',
       'snf_days_title_xviii', 'snf_days_total', 'snf_discharges_title_other',
       'snf_discharges_title_xix', 'snf_discharges_title_xviii',
       'snf_discharges_total', 'snf_number_of_beds', 'snf_bed_days_available',
       'salaries_wages_and_fees_payable', 'total_assets',
       'total_bed_days_available', 'total_costs', 'total_days_other',
       'total_days_title_xix', 'total_days_title_xviii', 'total_days_total',
       'total_discharges_title_other', 'total_discharges_title_xix',
       'total_discharges_title_xviii', 'total_discharges_total',
       'total_general_inpatient_revenue', 'total_income',
       'total_liab_and_fund_balances', 'total_rug_days',
       'total_salaries_from_worksheet_a', 'total_salaries_adjusted',
       'total_current_assets', 'total_current_liabilities',
       'total_fixed_assets', 'total_fund_balances', 'total_liabilities',
       'total_other_assets', 'wage_related_costs_core', 'fixed_equipment'],
      dtype='object')

In [18]:
filteredCostReport_2016 = costReport_2016[['rpt_rec_num', 'provider_ccn',
       'rural_versus_urban',
       'gross_revenue', 'inpatient_revenue',
       'net_income', 'net_income_from_patients',
       'net_patient_revenue', 'number_of_beds',
       'total_bed_days_available', 'total_costs','total_income',]]

In [52]:
filteredCostReport_2016

,rpt_rec_num,provider_ccn,rural_versus_urban,gross_revenue,inpatient_revenue,net_income,net_income_from_patients,net_patient_revenue,number_of_beds,total_bed_days_available,total_costs,total_income
0,1123428,75061,U,2579409.0,2579409.0,-206465.0,-207267.0,2437182.0,156.0,7176.0,261326.0,-206465.0
1,1123429,75185,U,1379340.0,1379340.0,-314472.0,-315511.0,966618.0,90.0,4140.0,154732.0,-314472.0
2,1126697,366429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1129197,515021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1132719,285295,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
15099,1344461,345343,U,31627133.0,31627133.0,156450.0,154592.0,11297180.0,130.0,47450.0,2739553.0,156450.0
15100,1346007,56078,U,27358398.0,27358398.0,704947.0,484442.0,9783566.0,99.0,36135.0,1832634.0,704947.0
15101,1346320,395582,U,33439473.0,33439473.0,794257.0,104583.0,29262731.0,297.0,108405.0,4220886.0,794257.0
15102,1354979,375556,U,1193266.0,1193266.0,-2820818.0,-2820818.0,1193266.0,NaN,NaN,625987.0,-2820818.0
15103,1358974,375472,U,5997606.0,5997606.0,-154511.0,-179075.0,2514553.0,48.0,17568.0,196155.0,-154513.0

In [20]:
filteredCostReport_2016.to_csv("filteredCostReport_2016.csv", index=False)

In [21]:
filteredCostReport_2015 = costReport_2015[['rpt_rec_num', 'provider_ccn',
       'rural_versus_urban','gross_revenue', 'inpatient_revenue',
       'net_income', 'net_income_from_patients',
       'net_patient_revenue', 'number_of_beds',
       'total_bed_days_available', 'total_costs','total_income']]

In [22]:
filteredCostReport_2015.columns.size

12

In [23]:
filteredCostReport_2015.to_csv("filteredCostReport_2015.csv", index=False)

In [24]:
costReport_2017 = pd.read_csv(r"/Users/brandonnguyen/Desktop/ACE_Project/2017_CostReport.csv")

In [25]:
costReport_2017.columns

Index(['rpt_rec_num', 'provider_ccn', 'facility_name', 'street_address',
       'city', 'state_code', 'zip_code', 'county', 'medicare_cbsa_number',
       'rural_versus_urban', 'fiscal_year_begin_date', 'fiscal_year_end_date',
       'type_of_control', 'accounts_receivable', 'accounts_payable',
       'buildings', 'cash_on_hand_and_in_banks', 'general_fund_balance',
       'gross_revenue', 'inpatient_pps_amount', 'inpatient_revenue',
       'less_total_operating_expense', 'less_discounts_on_patients',
       'major_movable_equipment', 'net_income', 'net_income_from_patients',
       'net_patient_revenue', 'number_of_beds', 'other_assets',
       'other_current_liabilities', 'overhead_non_salary_costs',
       'snf_admissions_other', 'snf_admissions_title_xix',
       'snf_admissions_title_xviii', 'snf_admissions_total',
       'snf_average_length_of_stay_tot', 'snf_average_length_stay_xix',
       'snf_average_length_stay_xviii', 'snf_days_other', 'snf_days_title_xix',
       'snf_days_title_xviii', 'snf_days_total', 'snf_discharges_title_other',
       'snf_discharges_title_xix', 'snf_discharges_title_xviii',
       'snf_discharges_total', 'snf_number_of_beds', 'snf_bed_days_available',
       'salaries_wages_and_fees_payable', 'total_assets',
       'total_bed_days_available', 'total_costs', 'total_days_other',
       'total_days_title_xix', 'total_days_title_xviii', 'total_days_total',
       'total_discharges_title_other', 'total_discharges_title_xix',
       'total_discharges_title_xviii', 'total_discharges_total',
       'total_general_inpatient_revenue', 'total_income',
       'total_liab_and_fund_balances', 'total_rug_days',
       'total_salaries_from_worksheet_a', 'total_salaries_adjusted',
       'total_current_assets', 'total_current_liabilities',
       'total_fixed_assets', 'total_fund_balances', 'total_liabilities',
       'total_other_assets', 'wage_related_costs_core', 'fixed_equipment'],
      dtype='object')

In [26]:
filteredCostReport_2017 = costReport_2017[['rpt_rec_num', 'provider_ccn',
       'rural_versus_urban','gross_revenue', 'inpatient_revenue',
       'net_income', 'net_income_from_patients',
       'net_patient_revenue', 'number_of_beds',
       'total_bed_days_available', 'total_costs','total_income']]

In [27]:
filteredCostReport_2017

,rpt_rec_num,provider_ccn,rural_versus_urban,gross_revenue,inpatient_revenue,net_income,net_income_from_patients,net_patient_revenue,number_of_beds,total_bed_days_available,total_costs,total_income
0,1156385,225718,U,1738186.0,1713518.0,47518.0,44056.0,1457745.0,142.0,4402.0,153260.0,47518.0
1,1157220,345507,U,3335776.0,3335776.0,262598.0,259951.0,2493657.0,110.0,10120.0,497304.0,262598.0
2,1157221,345222,U,3070058.0,3070058.0,256641.0,254434.0,2265128.0,120.0,11040.0,357104.0,256641.0
3,1157223,345567,U,3202836.0,3202836.0,154259.0,150633.0,2272596.0,102.0,9384.0,456310.0,154259.0
4,1159776,345269,U,3196761.0,3196761.0,134859.0,132621.0,2241251.0,100.0,9200.0,485065.0,134859.0
...,...,...,...,...,...,...,...,...,...,...,...,...
15428,1342926,255161,R,20790731.0,20790731.0,-2124321.0,-2124321.0,4366492.0,107.0,39055.0,1826657.0,-2124321.0
15429,1346257,425314,U,13537695.0,13537695.0,178113.0,-1078426.0,9062107.0,88.0,32120.0,1912870.0,178113.0
15430,1346418,215005,U,18517577.0,18517577.0,768137.0,744765.0,16135888.0,97.0,38412.0,6025084.0,768137.0
15431,1346803,445225,U,7085294.0,7085294.0,-515247.0,-515535.0,2850661.0,44.0,16940.0,1184626.0,-515247.0
15432,1355290,345205,R,17889632.0,17889632.0,930489.0,571491.0,13206070.0,186.0,67890.0,3268144.0,930489.0

In [28]:
filteredCostReport_2017.to_csv("filteredCostReport_2017.csv", index=False)

In [29]:
costReport_2018 = pd.read_csv(r"/Users/brandonnguyen/Desktop/ACE_Project/2018_CostReport.csv")

In [30]:
costReport_2018.columns

Index(['rpt_rec_num', 'provider_ccn', 'facility_name', 'street_address',
       'city', 'state_code', 'zip_code', 'county', 'medicare_cbsa_number',
       'rural_versus_urban', 'fiscal_year_begin_date', 'fiscal_year_end_date',
       'type_of_control', 'accounts_receivable', 'accounts_payable',
       'buildings', 'cash_on_hand_and_in_banks', 'general_fund_balance',
       'gross_revenue', 'inpatient_pps_amount', 'inpatient_revenue',
       'less_total_operating_expense', 'less_discounts_on_patients',
       'major_movable_equipment', 'net_income', 'net_income_from_patients',
       'net_patient_revenue', 'number_of_beds', 'other_assets',
       'other_current_liabilities', 'overhead_non_salary_costs',
       'snf_admissions_other', 'snf_admissions_title_xix',
       'snf_admissions_title_xviii', 'snf_admissions_total',
       'snf_average_length_of_stay_tot', 'snf_average_length_stay_xix',
       'snf_average_length_stay_xviii', 'snf_days_other', 'snf_days_title_xix',
       'snf_days_title_xviii', 'snf_days_total', 'snf_discharges_title_other',
       'snf_discharges_title_xix', 'snf_discharges_title_xviii',
       'snf_discharges_total', 'snf_number_of_beds', 'snf_bed_days_available',
       'salaries_wages_and_fees_payable', 'total_assets',
       'total_bed_days_available', 'total_costs', 'total_days_other',
       'total_days_title_xix', 'total_days_title_xviii', 'total_days_total',
       'total_discharges_title_other', 'total_discharges_title_xix',
       'total_discharges_title_xviii', 'total_discharges_total',
       'total_general_inpatient_revenue', 'total_income',
       'total_liab_and_fund_balances', 'total_rug_days',
       'total_salaries_from_worksheet_a', 'total_salaries_adjusted',
       'total_current_assets', 'total_current_liabilities',
       'total_fixed_assets', 'total_fund_balances', 'total_liabilities',
       'total_other_assets', 'wage_related_costs_core', 'fixed_equipment'],
      dtype='object')

In [31]:
filteredCostReport_2018 = costReport_2018[['rpt_rec_num', 'provider_ccn',
       'rural_versus_urban','gross_revenue', 'inpatient_revenue',
       'net_income', 'net_income_from_patients',
       'net_patient_revenue', 'number_of_beds',
       'total_bed_days_available', 'total_costs','total_income']]

In [33]:
filteredCostReport_2018.to_csv("filteredCostReport_2018.csv", index=False)

In [34]:
costReport_2019 = pd.read_csv(r"/Users/brandonnguyen/Desktop/ACE_Project/2019_CostReport.csv")

In [35]:
costReport_2019.columns

Index(['rpt_rec_num', 'provider_ccn', 'facility_name', 'street_address',
       'city', 'state_code', 'zip_code', 'county', 'medicare_cbsa_number',
       'rural_versus_urban', 'fiscal_year_begin_date', 'fiscal_year_end_date',
       'type_of_control', 'accounts_receivable', 'accounts_payable',
       'buildings', 'cash_on_hand_and_in_banks', 'general_fund_balance',
       'gross_revenue', 'inpatient_pps_amount', 'inpatient_revenue',
       'less_total_operating_expense', 'less_discounts_on_patients',
       'major_movable_equipment', 'net_income', 'net_income_from_patients',
       'net_patient_revenue', 'number_of_beds', 'other_assets',
       'other_current_liabilities', 'overhead_non_salary_costs',
       'snf_admissions_other', 'snf_admissions_title_xix',
       'snf_admissions_title_xviii', 'snf_admissions_total',
       'snf_average_length_of_stay_tot', 'snf_average_length_stay_xix',
       'snf_average_length_stay_xviii', 'snf_days_other', 'snf_days_title_xix',
       'snf_days_title_xviii', 'snf_days_total', 'snf_discharges_title_other',
       'snf_discharges_title_xix', 'snf_discharges_title_xviii',
       'snf_discharges_total', 'snf_number_of_beds', 'snf_bed_days_available',
       'salaries_wages_and_fees_payable', 'total_assets',
       'total_bed_days_available', 'total_costs', 'total_days_other',
       'total_days_title_xix', 'total_days_title_xviii', 'total_days_total',
       'total_discharges_title_other', 'total_discharges_title_xix',
       'total_discharges_title_xviii', 'total_discharges_total',
       'total_general_inpatient_revenue', 'total_income',
       'total_liab_and_fund_balances', 'total_rug_days',
       'total_salaries_from_worksheet_a', 'total_salaries_adjusted',
       'total_current_assets', 'total_current_liabilities',
       'total_fixed_assets', 'total_fund_balances', 'total_liabilities',
       'total_other_assets', 'wage_related_costs_core', 'fixed_equipment'],
      dtype='object')

In [36]:
filteredCostReport_2019 = costReport_2019[['rpt_rec_num', 'provider_ccn',
       'rural_versus_urban','gross_revenue', 'inpatient_revenue',
       'net_income', 'net_income_from_patients',
       'net_patient_revenue', 'number_of_beds',
       'total_bed_days_available', 'total_costs','total_income']]

In [38]:
filteredCostReport_2019.to_csv("filteredCostReport_2019.csv", index=False)

In [39]:
costReport_2020 = pd.read_csv(r"/Users/brandonnguyen/Desktop/ACE_Project/2020_CostReport.csv")

In [40]:
costReport_2020.columns

Index(['rpt_rec_num', 'provider_ccn', 'facility_name', 'street_address',
       'city', 'state_code', 'zip_code', 'county', 'medicare_cbsa_number',
       'rural_versus_urban',
       ...
       'less_contractual_allowance_and_discounts_on_patients'_accounts',
       'net_patient_revenue', 'less_total_operating_expense',
       'net_income_from_service_to_patients', 'total_other_income',
       'total_income', 'net_income', 'inpatient_pps_amount',
       'nursing_and_allied_health_education_activities',
       'allowable_bad_debts'],
      dtype='object', length=122)

In [41]:
costReport_2020

,rpt_rec_num,provider_ccn,facility_name,street_address,city,state_code,zip_code,county,medicare_cbsa_number,rural_versus_urban,...,less_contractual_allowance_and_discounts_on_patients'_accounts,net_patient_revenue,less_total_operating_expense,net_income_from_service_to_patients,total_other_income,total_income,net_income,inpatient_pps_amount,nursing_and_allied_health_education_activities,allowable_bad_debts
0,1254744,75031,GLEN HILL CENTER,1 GLEN HILL ROAD,DANBURY,CT,06811,FAIRFIELD,14860.0,U,...,712087.0,1083396.0,1023062.0,60334.0,50.0,60384.0,60384.0,476754.0,NaN,4814.0
1,1255877,495268,MARY WASHINGTON HEALTH CENTER,2400 MCKINNEY BLVD,COLONIAL BEACH,VA,22443,WESTMORELAND,99949.0,R,...,472648.0,814204.0,1076191.0,-261987.0,806.0,-261181.0,-261181.0,101663.0,NaN,NaN
2,1256270,295107,ADVANCED HEALTH CARE OF PARADISE,3455 PECOS-MCLEOD INTERCONNECT,LAS VEGAS,NV,89121,CLARK,29820.0,U,...,364289.0,1543399.0,1735321.0,-191922.0,120.0,-191802.0,-191802.0,1263318.0,NaN,NaN
3,1259169,146097,EL PASO HEALTH CARE CENTER,850 EAST SECOND STREET,EL PASO,IL,61738,WOODFORD,37900.0,U,...,183413.0,877453.0,914701.0,-37248.0,349.0,-36899.0,-36899.0,67241.0,NaN,3876.0
4,1259189,215136,BIRCH MANOR CTR FOR REHAB & HEALTHCA,7309 SECOND AVE,SYKESVILLE,MD,21784,CARROLL,12580.0,U,...,NaN,2038599.0,1880948.0,157651.0,20.0,157671.0,157671.0,342853.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14944,1363186,105382,SANDGATE GARDENS REHAB AND NURSING C,703 SOUTH 29TH STREET,FORT PIERCE,FL,34947,ST. LUCIE,38940.0,U,...,9567596.0,11533335.0,11888308.0,-354973.0,900214.0,545241.0,545241.0,4980305.0,NaN,1320104.0
14945,1363595,145970,THE VILLA AT WINDSOR PARK,2649 EAST 75TH STREET,CHICAGO,IL,60649,COOK,16974.0,U,...,205457.0,16610849.0,17102853.0,-492004.0,58322.0,-433682.0,-433682.0,3748730.0,NaN,292024.0
14946,1364413,375567,MEMORIAL NURSING CENTER,319 EAST JOSEPHINE,FREDERICK,OK,73542,TILLMAN,99937.0,R,...,NaN,1640531.0,2152408.0,-511877.0,NaN,-511877.0,-511877.0,43441.0,NaN,NaN
14947,1364622,415071,SOUTH COUNTY NURSING & REHAB CENTER,740 OAK HILL ROAD,NORTH KINGSTOWN,RI,02852,WASHINGTON,39300.0,U,...,1010345.0,2999135.0,3542544.0,-543409.0,1595.0,-541814.0,-541814.0,351597.0,NaN,NaN
14948,1365542,56261,MERRITT MANOR CONVALESCENT HOSPITAL,604 EAST MERRITT AVENUE,TULARE,CA,93274,TULARE,47300.0,U,...,-1394622.0,9213000.0,10026931.0,-813931.0,754998.0,-58933.0,-89357.0,4823966.0,NaN,NaN

In [43]:
filteredCostReport_2020 = costReport_2020[['rpt_rec_num', 'provider_ccn',
       'rural_versus_urban','gross_revenue', 'inpatient_revenue',
       'net_income', 'net_income_from_service_to_patients',
       'net_patient_revenue', 'number_of_beds',
       'total_bed_days_available', 'total_costs','total_income']]

In [44]:
filteredCostReport_2020

,rpt_rec_num,provider_ccn,rural_versus_urban,gross_revenue,inpatient_revenue,net_income,net_income_from_service_to_patients,net_patient_revenue,number_of_beds,total_bed_days_available,total_costs,total_income
0,1254744,75031,U,1795483.0,1795483.0,60384.0,60334.0,1083396.0,100.0,3100.0,195203.0,60384.0
1,1255877,495268,R,1286852.0,1286852.0,-261181.0,-261987.0,814204.0,66.0,3894.0,210445.0,-261181.0
2,1256270,295107,U,1907688.0,1906805.0,-191802.0,-191922.0,1543399.0,38.0,3382.0,492172.0,-191802.0
3,1259169,146097,U,1060866.0,1060866.0,-36899.0,-37248.0,877453.0,123.0,7749.0,42549.0,-36899.0
4,1259189,215136,U,2038599.0,2038599.0,157671.0,157651.0,2038599.0,118.0,7198.0,222656.0,157671.0
...,...,...,...,...,...,...,...,...,...,...,...,...
14944,1363186,105382,U,21100931.0,21100931.0,545241.0,-354973.0,11533335.0,107.0,39162.0,1585761.0,545241.0
14945,1363595,145970,U,16816306.0,16816306.0,-433682.0,-492004.0,16610849.0,240.0,87840.0,1322483.0,-433682.0
14946,1364413,375567,R,1640531.0,1640531.0,-511877.0,-511877.0,1640531.0,NaN,NaN,16221.0,-511877.0
14947,1364622,415071,U,4009480.0,4009480.0,-541814.0,-543409.0,2999135.0,120.0,22080.0,363700.0,-541814.0
14948,1365542,56261,U,7818378.0,7818378.0,-89357.0,-813931.0,9213000.0,99.0,36234.0,990470.0,-58933.0

In [45]:
filteredCostReport_2020.to_csv("filteredCostReport_2020.csv", index=False)

In [46]:
costReport_2021 = pd.read_csv(r"/Users/brandonnguyen/Desktop/ACE_Project/2021_CostReport.csv")

In [47]:
costReport_2021.columns

Index(['rpt_rec_num', 'provider_ccn', 'facility_name', 'street_address',
       'city', 'state_code', 'zip_code', 'county', 'medicare_cbsa_number',
       'rural_versus_urban',
       ...
       'less_contractual_allowance_and_discounts_on_patients'_accounts',
       'net_patient_revenue', 'less_total_operating_expense',
       'net_income_from_service_to_patients', 'total_other_income',
       'total_income', 'net_income', 'inpatient_pps_amount',
       'nursing_and_allied_health_education_activities',
       'allowable_bad_debts'],
      dtype='object', length=122)

In [48]:
filteredCostReport_2021 = costReport_2021[['rpt_rec_num', 'provider_ccn',
       'rural_versus_urban','gross_revenue', 'inpatient_revenue',
       'net_income', 'net_income_from_service_to_patients',
       'net_patient_revenue', 'number_of_beds',
       'total_bed_days_available', 'total_costs','total_income']]

In [49]:
costReport_2021

,rpt_rec_num,provider_ccn,facility_name,street_address,city,state_code,zip_code,county,medicare_cbsa_number,rural_versus_urban,...,less_contractual_allowance_and_discounts_on_patients'_accounts,net_patient_revenue,less_total_operating_expense,net_income_from_service_to_patients,total_other_income,total_income,net_income,inpatient_pps_amount,nursing_and_allied_health_education_activities,allowable_bad_debts
0,1289595,305005,GREENBRIAR HEALTHCARE,55 HARRIS ROAD,NASHUA,NH,03062,HILLSBOROUGH,31700.0,U,...,-105598.0,2736656.0,2438116.0,298540.0,NaN,298540.0,298540.0,583183.0,NaN,NaN
1,1290123,396142,PARAMOUNT NURSING & REHAB SOUTH HILL,100 KNOEDLER RD,PITTSBURGH,PA,15236,ALLEGHENY,38300.0,U,...,120004.0,265111.0,473381.0,-208270.0,NaN,-208270.0,-208270.0,117121.0,NaN,NaN
2,1291767,265001,TOWN & COUNTRY HEALTH & REHAB,13995 CLAYTON ROAD,TOWN & COUNTRY,MO,63017,ST. LOUIS,41180.0,U,...,124964.0,1356995.0,1369656.0,-12661.0,3168.0,-9493.0,-9493.0,447307.0,NaN,NaN
3,1292383,275080,HELENA NURSING AND REHAB CENTER LLC,2555 EAST BROADWAY,HELENA,MT,59601,LEWIS AND CLARK,99927.0,R,...,51498.0,2484229.0,2297000.0,187229.0,7961.0,195190.0,195190.0,655919.0,NaN,NaN
4,1294159,75102,MERIDIAN MANOR,1132 MERIDIAN ROAD,WATERBURY,CT,06705,NEW HAVEN,35300.0,U,...,13348.0,658667.0,869914.0,-211247.0,12607.0,-198640.0,-198640.0,24074.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15052,1365869,505453,KIN ON HEALTH CARE CENTER,4416 SOUTH BRANDON,SEATTLE,WA,98118,KING,42644.0,U,...,690392.0,8661500.0,9750271.0,-1088771.0,129009.0,-959762.0,-959762.0,720665.0,NaN,66284.0
15053,1365888,675765,LCS-WP LLC DBA WALNUT PLACE,5515 GLEN LAKES DRIVE,DALLAS,TX,75231,DALLAS,19124.0,U,...,2034837.0,12808233.0,14911931.0,-2103698.0,1263196.0,-840502.0,-840502.0,3405586.0,NaN,NaN
15054,1365889,675932,STRATFORD HOSPITAL DISTRICT DBA ARBO,609 RIO CONCHO DRIVE,SAN ANGELO,TX,76903-6029,TOM GREEN,41660.0,U,...,1531379.0,7477706.0,6086547.0,1391159.0,525534.0,1916693.0,1916693.0,2087939.0,NaN,35636.0
15055,1365890,675956,WINDSOR NRS & REHAB CTR OF DUVAL,5301 W. DUVAL ROAD,AUSTIN,TX,78727,TRAVIS,12420.0,U,...,NaN,12738362.0,15288127.0,-2549765.0,3738132.0,1188367.0,1188367.0,2228244.0,NaN,81397.0
15056,1365892,676481,BETHANY SENIOR LIVING,118 TRINITY SHORES DR,PORT LAVACA,TX,77979,CALHOUN,99945.0,R,...,NaN,9991720.0,9536736.0,454984.0,284868.0,739852.0,739852.0,3922613.0,NaN,14049.0

In [50]:
filteredCostReport_2021

,rpt_rec_num,provider_ccn,rural_versus_urban,gross_revenue,inpatient_revenue,net_income,net_income_from_service_to_patients,net_patient_revenue,number_of_beds,total_bed_days_available,total_costs,total_income
0,1289595,305005,U,2631058.0,2631058.0,298540.0,298540.0,2736656.0,290.0,17690.0,359371.0,298540.0
1,1290123,396142,U,385115.0,385115.0,-208270.0,-208270.0,265111.0,17.0,1530.0,99841.0,-208270.0
2,1291767,265001,U,1481959.0,1481959.0,-9493.0,-12661.0,1356995.0,282.0,12972.0,157659.0,-9493.0
3,1292383,275080,R,2535727.0,2535727.0,195190.0,187229.0,2484229.0,90.0,8280.0,364077.0,195190.0
4,1294159,75102,U,672015.0,672015.0,-198640.0,-211247.0,658667.0,94.0,9306.0,24711.0,-198640.0
...,...,...,...,...,...,...,...,...,...,...,...,...
15052,1365869,505453,U,9351892.0,9351892.0,-959762.0,-1088771.0,8661500.0,100.0,36500.0,357017.0,-959762.0
15053,1365888,675765,U,14843070.0,14843070.0,-840502.0,-2103698.0,12808233.0,388.0,141620.0,2312210.0,-840502.0
15054,1365889,675932,U,9009085.0,8599523.0,1916693.0,1391159.0,7477706.0,126.0,45990.0,1111339.0,1916693.0
15055,1365890,675956,U,12738362.0,12738362.0,1188367.0,-2549765.0,12738362.0,206.0,75190.0,1250246.0,1188367.0
15056,1365892,676481,R,9991720.0,9991720.0,739852.0,454984.0,9991720.0,130.0,47450.0,1493029.0,739852.0

In [51]:
filteredCostReport_2021.to_csv("filteredCostReport_2021.csv", index=False)

In [53]:
filteredCostReport_2021.rename(columns={'net_income_from_service_to_patients': 'net_income_from_patients'}, inplace=True)

/var/folders/7t/7qf1whc969jcpbccjdpbv57r0000gn/T/ipykernel_4460/3707430048.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filteredCostReport_2021.rename(columns={'net_income_from_service_to_patients': 'net_income_from_patients'}, inplace=True)

In [54]:
filteredCostReport_2021 = filteredCostReport_2021.rename(columns={'net_income_from_service_to_patients': 'net_income_from_patients'})

In [55]:
filteredCostReport_2021

,rpt_rec_num,provider_ccn,rural_versus_urban,gross_revenue,inpatient_revenue,net_income,net_income_from_patients,net_patient_revenue,number_of_beds,total_bed_days_available,total_costs,total_income
0,1289595,305005,U,2631058.0,2631058.0,298540.0,298540.0,2736656.0,290.0,17690.0,359371.0,298540.0
1,1290123,396142,U,385115.0,385115.0,-208270.0,-208270.0,265111.0,17.0,1530.0,99841.0,-208270.0
2,1291767,265001,U,1481959.0,1481959.0,-9493.0,-12661.0,1356995.0,282.0,12972.0,157659.0,-9493.0
3,1292383,275080,R,2535727.0,2535727.0,195190.0,187229.0,2484229.0,90.0,8280.0,364077.0,195190.0
4,1294159,75102,U,672015.0,672015.0,-198640.0,-211247.0,658667.0,94.0,9306.0,24711.0,-198640.0
...,...,...,...,...,...,...,...,...,...,...,...,...
15052,1365869,505453,U,9351892.0,9351892.0,-959762.0,-1088771.0,8661500.0,100.0,36500.0,357017.0,-959762.0
15053,1365888,675765,U,14843070.0,14843070.0,-840502.0,-2103698.0,12808233.0,388.0,141620.0,2312210.0,-840502.0
15054,1365889,675932,U,9009085.0,8599523.0,1916693.0,1391159.0,7477706.0,126.0,45990.0,1111339.0,1916693.0
15055,1365890,675956,U,12738362.0,12738362.0,1188367.0,-2549765.0,12738362.0,206.0,75190.0,1250246.0,1188367.0
15056,1365892,676481,R,9991720.0,9991720.0,739852.0,454984.0,9991720.0,130.0,47450.0,1493029.0,739852.0

In [56]:
filteredCostReport_2021.to_csv("filteredCostReport_2021.csv", index=False)

In [57]:
filteredCostReport_2020 = filteredCostReport_2020.rename(columns={'net_income_from_service_to_patients': 'net_income_from_patients'})

In [58]:
filteredCostReport_2020

,rpt_rec_num,provider_ccn,rural_versus_urban,gross_revenue,inpatient_revenue,net_income,net_income_from_patients,net_patient_revenue,number_of_beds,total_bed_days_available,total_costs,total_income
0,1254744,75031,U,1795483.0,1795483.0,60384.0,60334.0,1083396.0,100.0,3100.0,195203.0,60384.0
1,1255877,495268,R,1286852.0,1286852.0,-261181.0,-261987.0,814204.0,66.0,3894.0,210445.0,-261181.0
2,1256270,295107,U,1907688.0,1906805.0,-191802.0,-191922.0,1543399.0,38.0,3382.0,492172.0,-191802.0
3,1259169,146097,U,1060866.0,1060866.0,-36899.0,-37248.0,877453.0,123.0,7749.0,42549.0,-36899.0
4,1259189,215136,U,2038599.0,2038599.0,157671.0,157651.0,2038599.0,118.0,7198.0,222656.0,157671.0
...,...,...,...,...,...,...,...,...,...,...,...,...
14944,1363186,105382,U,21100931.0,21100931.0,545241.0,-354973.0,11533335.0,107.0,39162.0,1585761.0,545241.0
14945,1363595,145970,U,16816306.0,16816306.0,-433682.0,-492004.0,16610849.0,240.0,87840.0,1322483.0,-433682.0
14946,1364413,375567,R,1640531.0,1640531.0,-511877.0,-511877.0,1640531.0,NaN,NaN,16221.0,-511877.0
14947,1364622,415071,U,4009480.0,4009480.0,-541814.0,-543409.0,2999135.0,120.0,22080.0,363700.0,-541814.0
14948,1365542,56261,U,7818378.0,7818378.0,-89357.0,-813931.0,9213000.0,99.0,36234.0,990470.0,-58933.0

In [59]:
filteredCostReport_2020.to_csv("filteredCostReport_2020.csv", index=False)

# Provider Info Cleaning

In [60]:
providerInfo_2015 = pd.read_csv(r"/Users/brandonnguyen/Desktop/ACE_Project/ProviderInfo_2015.csv")

In [61]:
providerInfo_2015

,rpt_rec_num,provider_ccn,facility_name,street_address,city,state_code,zip_code,county,medicare_cbsa_number,rural_versus_urban,...,total_salaries_from_worksheet_a,total_salaries_adjusted,total_current_assets,total_current_liabilities,total_fixed_assets,total_fund_balances,total_liabilities,total_other_assets,wage_related_costs_core,fixed_equipment
0,1226920,525009,CROSSROADS CARE CENTER OF EAST GREEN,600 S WEBSTER AVENUE,GREEN BAY,WI,54301,BROWN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1228236,45228,MAPLE HEALTHCARE,200 S MAPLE STREET,HAZEN,AR,72064,PRAIRIE,99904.0,R,...,199985.0,199985.0,95653.0,94275.0,5906.0,17284.0,94275.0,10000.0,24783.0,NaN
2,1230331,435123,GOOD SAMARITAN SOCIETY-SELBY,4861 LINCOLN AVE,SELBY,SD,57472-0299,WALWORHT,99943.0,R,...,196753.0,196753.0,412380.0,237612.0,2528.0,183543.0,237612.0,6247.0,56833.0,NaN
3,1232670,525232,CCC OF WEST GREEN BAY LLC,1760 SHAWANO AVENUE,GREEN BAY,WI,54303,BROWN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1235138,35270,LA ESTANCIA NURSING & REHAB CENTER,15810 SOUTH 42ND STREET,PHOENIX,AZ,85048,MARICOPA,38060.0,U,...,670243.0,670243.0,1476169.0,489058.0,4265304.0,71252.0,4885852.0,-784369.0,100340.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15177,1347594,395628,RENAISSANCE HEALTHCARE & REHAB,4712 CHESTER AVE,PHILADELPHIA,PA,19072,PHILADELPHIA,37964.0,U,...,4778746.0,4778746.0,1801560.0,1655963.0,267303.0,-1264536.0,3333399.0,NaN,917022.0,544227.0
15178,1350728,396122,FOX SUBACUTE CTR AT MECHANICSBURG,120 SOUTH FILBERT STREET,MECHANICSBURG,PA,17055,CUMBERLAND,25420.0,U,...,5416031.0,5416031.0,4944418.0,6598103.0,452041.0,-2776447.0,8172906.0,NaN,1001048.0,30367.0
15179,1352460,396141,FOX SUBACUTE AT SOUTH PHILADELPHIA,1930 SOUTH BROAD STREET,PHILADELPHIA,PA,19145,PHILADELPHIA,37964.0,U,...,4928756.0,4928756.0,4760248.0,3460167.0,366666.0,-2285039.0,3460167.0,-3951786.0,784321.0,NaN
15180,1356468,345205,WESTWOOD HILLS NURSING & REHAB CTR,1016 FLETCHER STREET,WILKESBORO,NC,28697,WILKES,99934.0,R,...,4556977.0,4556977.0,11166295.0,415426.0,76650.0,10827519.0,415426.0,NaN,1258262.0,1175623.0
15181,1364900,375567,MEMORIAL NURSING CENTER,319 EAST JOSEPHINE,FREDERICK,OK,73542,TILLMAN,99937.0,R,...,1353890.0,1353890.0,220297.0,211650.0,NaN,8647.0,211650.0,NaN,160171.0,NaN

In [62]:
providerInfo_2016 = pd.read_csv(r"/Users/brandonnguyen/Desktop/ACE_Project/ProviderInfo_2016.csv")

In [63]:
providerInfo_2016

,provnum,provname,address,city,state,zip,phone,county_ssa,county_name,ownership,...,cycle_3_revisit_score,cycle_3_total_score,weighted_all_cycles_score,incident_cnt,cmplnt_cnt,fine_cnt,fine_tot,payden_cnt,tot_penlty_cnt,filedate
0,015009,"BURNS NURSING HOME, INC.",701 MONROE STREET NW,RUSSELLVILLE,AL,35653,2563324110,290,Franklin,For profit - Corporation,...,0,16,12.000,0,0,0,0,0,0,2016-12-01
1,015010,COOSA VALLEY NURSING FACILITY,315 WEST HICKORY STREET,SYLACAUGA,AL,35150,2562495604,600,Talladega,Non profit - Other,...,0,32,34.667,0,0,1,15259,1,2,2016-12-01
2,015012,HIGHLANDS HEALTH AND REHAB,380 WOODS COVE ROAD,SCOTTSBORO,AL,35768,2562183708,350,Jackson,Government - County,...,0,20,14.667,0,0,0,0,0,0,2016-12-01
3,015014,EASTVIEW REHABILITATION & HEALTHCARE CENTER,7755 FOURTH AVENUE SOUTH,BIRMINGHAM,AL,35206,2058330146,360,Jefferson,For profit - Corporation,...,0,24,38.000,0,1,0,0,0,0,2016-12-01
4,015015,PLANTATION MANOR NURSING HOME,6450 OLD TUSCALOOSA HIGHWAY P O BOX 97,MC CALLA,AL,35111,2054776161,360,Jefferson,For profit - Partnership,...,0,24,33.333,0,0,0,0,0,0,2016-12-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15646,676393,LAS VENTANAS DE SOCORRO,10064 ALAMEDA AVENUE,SOCORRO,TX,79927,9157730730,480,El Paso,For profit - Corporation,...,.,.,.,1,1,0,0,0,0,2016-12-01
15647,676394,WOODLANDS PLACE REHABILITATION SUITES,5600 WOODLANDS TRAIL,DENISON,TX,75020,9034621200,564,Grayson,For profit - Corporation,...,.,.,.,0,0,0,0,0,0,2016-12-01
15648,676395,THE HEALTHCARE RESORT OF PLANO,3325 WEST PLANO PARKWAY,PLANO,TX,75075,9725961260,310,Collin,For profit - Individual,...,.,.,.,0,0,0,0,0,0,2016-12-01
15649,676396,S.P.J.S.T. REST HOME 3,248 WISTERIA LANE,EL CAMPO,TX,77437,9796482628,954,Wharton,Non profit - Corporation,...,.,.,.,0,0,0,0,0,0,2016-12-01
15650,676398,THE RIO AT FOX HOLLOW,310 AMERICA DRIVE,BROWNSVILLE,TX,78526,9565743400,240,Cameron,For profit - Partnership,...,.,.,.,0,2,0,0,0,0,2016-12-01

In [64]:
providerInfo_2016.columns

Index(['provnum', 'provname', 'address', 'city', 'state', 'zip', 'phone',
       'county_ssa', 'county_name', 'ownership', 'bedcert', 'restot',
       'certification', 'inhosp', 'lbn', 'participation_date', 'ccrc_facil',
       'sff', 'oldsurvey', 'chow_last_12mos', 'resfamcouncil',
       'sprinkler_status', 'overall_rating', 'overall_rating_fn',
       'survey_rating', 'survey_rating_fn', 'quality_rating',
       'quality_rating_fn', 'staffing_rating', 'staffing_rating_fn',
       'rn_staffing_rating', 'rn_staffing_rating_fn', 'staffing_flag',
       'pt_staffing_flag', 'aidhrd', 'vochrd', 'rnhrd', 'totlichrd', 'tothrd',
       'pthrd', 'exp_aide', 'exp_lpn', 'exp_rn', 'exp_total', 'adj_aide',
       'adj_lpn', 'adj_rn', 'adj_total', 'cycle_1_defs', 'cycle_1_nfromdefs',
       'cycle_1_nfromcomp', 'cycle_1_defs_score', 'cycle_1_survey_date',
       'cycle_1_numrevis', 'cycle_1_revisit_score', 'cycle_1_total_score',
       'cycle_2_defs', 'cycle_2_nfromdefs', 'cycle_2_nfromcomp',
       'cycle_2_defs_score', 'cycle_2_survey_date', 'cycle_2_numrevis',
       'cycle_2_revisit_score', 'cycle_2_total_score', 'cycle_3_defs',
       'cycle_3_nfromdefs', 'cycle_3_nfromcomp', 'cycle_3_defs_score',
       'cycle_3_survey_date', 'cycle_3_numrevis', 'cycle_3_revisit_score',
       'cycle_3_total_score', 'weighted_all_cycles_score', 'incident_cnt',
       'cmplnt_cnt', 'fine_cnt', 'fine_tot', 'payden_cnt', 'tot_penlty_cnt',
       'filedate'],
      dtype='object')

In [67]:
filteredProvierInfo_2016 = providerInfo_2016[['provnum', 'provname', 'address', 'city', 'state', 'zip','ownership','restot',
       'overall_rating','survey_rating','quality_rating',
       'staffing_rating','adj_total' ]]

In [68]:
filteredProvierInfo_2016

,provnum,provname,address,city,state,zip,ownership,restot,overall_rating,survey_rating,quality_rating,staffing_rating,adj_total
0,015009,"BURNS NURSING HOME, INC.",701 MONROE STREET NW,RUSSELLVILLE,AL,35653,For profit - Corporation,45,5.0,5.0,3.0,5.0,4.49813
1,015010,COOSA VALLEY NURSING FACILITY,315 WEST HICKORY STREET,SYLACAUGA,AL,35150,Non profit - Other,82,3.0,2.0,4.0,4.0,4.00595
2,015012,HIGHLANDS HEALTH AND REHAB,380 WOODS COVE ROAD,SCOTTSBORO,AL,35768,Government - County,44,4.0,4.0,3.0,3.0,4.62351
3,015014,EASTVIEW REHABILITATION & HEALTHCARE CENTER,7755 FOURTH AVENUE SOUTH,BIRMINGHAM,AL,35206,For profit - Corporation,82,3.0,2.0,2.0,4.0,4.81469
4,015015,PLANTATION MANOR NURSING HOME,6450 OLD TUSCALOOSA HIGHWAY P O BOX 97,MC CALLA,AL,35111,For profit - Partnership,97,3.0,2.0,2.0,4.0,4.40793
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15646,676393,LAS VENTANAS DE SOCORRO,10064 ALAMEDA AVENUE,SOCORRO,TX,79927,For profit - Corporation,3,NaN,NaN,NaN,NaN,NaN
15647,676394,WOODLANDS PLACE REHABILITATION SUITES,5600 WOODLANDS TRAIL,DENISON,TX,75020,For profit - Corporation,3,NaN,NaN,NaN,NaN,NaN
15648,676395,THE HEALTHCARE RESORT OF PLANO,3325 WEST PLANO PARKWAY,PLANO,TX,75075,For profit - Individual,3,NaN,NaN,NaN,NaN,NaN
15649,676396,S.P.J.S.T. REST HOME 3,248 WISTERIA LANE,EL CAMPO,TX,77437,Non profit - Corporation,37,NaN,NaN,NaN,NaN,NaN
15650,676398,THE RIO AT FOX HOLLOW,310 AMERICA DRIVE,BROWNSVILLE,TX,78526,For profit - Partnership,2,NaN,NaN,NaN,NaN,NaN

In [70]:
filteredProvierInfo_2016.to_csv("filteredProviderInfo_2016.csv", index=False)

In [71]:
providerInfo_2017 = pd.read_csv(r"/Users/brandonnguyen/Desktop/ACE_Project/ProviderInfo_2017.csv")

In [72]:
providerInfo_2017

,provnum,provname,address,city,state,zip,phone,county_ssa,county_name,ownership,...,cycle_2_revisit_score,cycle_2_total_score,weighted_all_cycles_score,incident_cnt,cmplnt_cnt,fine_cnt,fine_tot,payden_cnt,tot_penlty_cnt,filedate
0,015009,"BURNS NURSING HOME, INC.",701 MONROE STREET NW,RUSSELLVILLE,AL,35653,2563324110,290,Franklin,For profit - Corporation,...,0,8,3.200,0,0,0,0,0,0,2018-12-01
1,015010,COOSA VALLEY NURSING FACILITY,315 WEST HICKORY STREET,SYLACAUGA,AL,35150,2562495604,600,Talladega,Non profit - Other,...,0,16,28.000,0,0,1,15259,1,2,2018-12-01
2,015012,HIGHLANDS HEALTH AND REHAB,380 WOODS COVE ROAD,SCOTTSBORO,AL,35768,2562183708,350,Jackson,Government - County,...,0,12,31.200,0,0,0,0,0,0,2018-12-01
3,015014,EASTVIEW REHABILITATION & HEALTHCARE CENTER,7755 FOURTH AVENUE SOUTH,BIRMINGHAM,AL,35206,2058330146,360,Jefferson,For profit - Corporation,...,0,24,33.600,0,1,0,0,0,0,2018-12-01
4,015015,PLANTATION MANOR NURSING HOME,6450 OLD TUSCALOOSA HIGHWAY P O BOX 97,MC CALLA,AL,35111,2054776161,360,Jefferson,For profit - Corporation,...,0,24,19.200,0,0,1,22903,0,1,2018-12-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15591,676449,RAPID RECOVERY CENTER OF FORT WORTH,6301 OAKMONT BLVD,FORT WORTH,TX,76132,6823128577,910,Tarrant,For profit - Corporation,...,.,.,.,0,0,0,0,0,0,2018-12-01
15592,676450,TERRA BELLA HEALTH AND WELLNESS SUITES,12262 CITYSCAPE AVE,HOUSTON,TX,77047,3469983500,610,Harris,For profit - Corporation,...,.,.,.,0,0,0,0,0,0,2018-12-01
15593,676451,ADORA MIDTOWN PARK,8130 MEADOW RD,DALLAS,TX,75231,2147653300,390,Dallas,For profit - Corporation,...,.,.,.,0,0,0,0,0,0,2018-12-01
15594,676452,ALLEGIANT WELLNESS AND REHAB,724 W. RENDON CROWLEY ROAD,CROWLEY,TX,76036,8172974141,910,Tarrant,For profit - Partnership,...,.,.,.,0,0,0,0,0,0,2018-12-01
15595,676453,SIMPSON PLACE,3922 SIMPSON STREET,DALLAS,TX,75246,2142310864,390,Dallas,For profit - Partnership,...,.,.,.,0,0,0,0,0,0,2018-12-01

In [73]:
filteredProvierInfo_2017 = providerInfo_2017[['provnum', 'provname', 'address', 'city', 'state', 'zip','ownership','restot',
       'overall_rating','survey_rating','quality_rating',
       'staffing_rating','adj_total' ]]

In [74]:
filteredProvierInfo_2017

,provnum,provname,address,city,state,zip,ownership,restot,overall_rating,survey_rating,quality_rating,staffing_rating,adj_total
0,015009,"BURNS NURSING HOME, INC.",701 MONROE STREET NW,RUSSELLVILLE,AL,35653,For profit - Corporation,52.6,5.0,5.0,5.0,4.0,4.88972
1,015010,COOSA VALLEY NURSING FACILITY,315 WEST HICKORY STREET,SYLACAUGA,AL,35150,Non profit - Other,NaN,3.0,3.0,5.0,1.0,NaN
2,015012,HIGHLANDS HEALTH AND REHAB,380 WOODS COVE ROAD,SCOTTSBORO,AL,35768,Government - County,46.6,3.0,2.0,2.0,5.0,4.98327
3,015014,EASTVIEW REHABILITATION & HEALTHCARE CENTER,7755 FOURTH AVENUE SOUTH,BIRMINGHAM,AL,35206,For profit - Corporation,82.3,2.0,2.0,4.0,3.0,3.94427
4,015015,PLANTATION MANOR NURSING HOME,6450 OLD TUSCALOOSA HIGHWAY P O BOX 97,MC CALLA,AL,35111,For profit - Corporation,98.4,4.0,3.0,5.0,3.0,3.75173
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15591,676449,RAPID RECOVERY CENTER OF FORT WORTH,6301 OAKMONT BLVD,FORT WORTH,TX,76132,For profit - Corporation,NaN,NaN,NaN,NaN,NaN,NaN
15592,676450,TERRA BELLA HEALTH AND WELLNESS SUITES,12262 CITYSCAPE AVE,HOUSTON,TX,77047,For profit - Corporation,NaN,NaN,NaN,NaN,NaN,NaN
15593,676451,ADORA MIDTOWN PARK,8130 MEADOW RD,DALLAS,TX,75231,For profit - Corporation,NaN,NaN,NaN,NaN,NaN,NaN
15594,676452,ALLEGIANT WELLNESS AND REHAB,724 W. RENDON CROWLEY ROAD,CROWLEY,TX,76036,For profit - Partnership,NaN,NaN,NaN,NaN,NaN,NaN
15595,676453,SIMPSON PLACE,3922 SIMPSON STREET,DALLAS,TX,75246,For profit - Partnership,NaN,NaN,NaN,NaN,NaN,NaN

In [75]:
filteredProvierInfo_2017.to_csv("filteredProviderInfo_2017.csv", index=False)

In [76]:
providerInfo_2018 = pd.read_csv(r"/Users/brandonnguyen/Desktop/ACE_Project/ProviderInfo_2018.csv")

In [77]:
providerInfo_2018

,provnum,provname,address,city,state,zip,phone,county_ssa,county_name,ownership,...,cycle_2_revisit_score,cycle_2_total_score,weighted_all_cycles_score,incident_cnt,cmplnt_cnt,fine_cnt,fine_tot,payden_cnt,tot_penlty_cnt,filedate
0,015009,"BURNS NURSING HOME, INC.",701 MONROE STREET NW,RUSSELLVILLE,AL,35653,2563324110,290,Franklin,For profit - Corporation,...,0,8,3.200,0,0,0,0,0,0,2018-12-01
1,015010,COOSA VALLEY NURSING FACILITY,315 WEST HICKORY STREET,SYLACAUGA,AL,35150,2562495604,600,Talladega,Non profit - Other,...,0,16,28.000,0,0,1,15259,1,2,2018-12-01
2,015012,HIGHLANDS HEALTH AND REHAB,380 WOODS COVE ROAD,SCOTTSBORO,AL,35768,2562183708,350,Jackson,Government - County,...,0,12,31.200,0,0,0,0,0,0,2018-12-01
3,015014,EASTVIEW REHABILITATION & HEALTHCARE CENTER,7755 FOURTH AVENUE SOUTH,BIRMINGHAM,AL,35206,2058330146,360,Jefferson,For profit - Corporation,...,0,24,33.600,0,1,0,0,0,0,2018-12-01
4,015015,PLANTATION MANOR NURSING HOME,6450 OLD TUSCALOOSA HIGHWAY P O BOX 97,MC CALLA,AL,35111,2054776161,360,Jefferson,For profit - Corporation,...,0,24,19.200,0,0,1,22903,0,1,2018-12-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15591,676449,RAPID RECOVERY CENTER OF FORT WORTH,6301 OAKMONT BLVD,FORT WORTH,TX,76132,6823128577,910,Tarrant,For profit - Corporation,...,.,.,.,0,0,0,0,0,0,2018-12-01
15592,676450,TERRA BELLA HEALTH AND WELLNESS SUITES,12262 CITYSCAPE AVE,HOUSTON,TX,77047,3469983500,610,Harris,For profit - Corporation,...,.,.,.,0,0,0,0,0,0,2018-12-01
15593,676451,ADORA MIDTOWN PARK,8130 MEADOW RD,DALLAS,TX,75231,2147653300,390,Dallas,For profit - Corporation,...,.,.,.,0,0,0,0,0,0,2018-12-01
15594,676452,ALLEGIANT WELLNESS AND REHAB,724 W. RENDON CROWLEY ROAD,CROWLEY,TX,76036,8172974141,910,Tarrant,For profit - Partnership,...,.,.,.,0,0,0,0,0,0,2018-12-01
15595,676453,SIMPSON PLACE,3922 SIMPSON STREET,DALLAS,TX,75246,2142310864,390,Dallas,For profit - Partnership,...,.,.,.,0,0,0,0,0,0,2018-12-01

In [78]:
filteredProvierInfo_2018 = providerInfo_2018[['provnum', 'provname', 'address', 'city', 'state', 'zip','ownership','restot',
       'overall_rating','survey_rating','quality_rating',
       'staffing_rating','adj_total' ]]

In [80]:
filteredProvierInfo_2018.to_csv("filteredProviderInfo_2018.csv", index=False)

In [81]:
providerInfo_2019 = pd.read_csv(r"/Users/brandonnguyen/Desktop/ACE_Project/ProviderInfo_2019.csv")

In [83]:
filteredProvierInfo_2019 = providerInfo_2019[['provnum', 'provname', 'address', 'city', 'state', 'zip','ownership','restot',
       'overall_rating','survey_rating','quality_rating',
       'staffing_rating','adj_total' ]]

In [85]:
filteredProvierInfo_2019.to_csv("filteredProviderInfo_2019.csv", index=False)

In [86]:
providerInfo_2020 = pd.read_csv(r"/Users/brandonnguyen/Desktop/ACE_Project/ProviderInfo_2020.csv")

In [87]:
providerInfo_2020

,federal_provider_number,provider_name,provider_address,provider_city,provider_state,provider_zip_code,provider_phone_number,provider_ssa_county_code,provider_county_name,ownership_type,...,rating_cycle_3_total_health_score,total_weighted_health_survey_score,number_of_facility_reported_incidents,number_of_substantiated_complaints,number_of_fines,total_amount_of_fines_in_dollars,number_of_payment_denials,total_number_of_penalties,location,processing_date
0,015009,"BURNS NURSING HOME, INC.",701 MONROE STREET NW,RUSSELLVILLE,AL,35653,2563324110,290,Franklin,For profit - Corporation,...,0,5.333,0,0,0,0,0,0,"701 MONROE STREET NW,RUSSELLVILLE,AL,35653",2020-11-01
1,015010,COOSA VALLEY HEALTHCARE CENTER,260 WEST WALNUT STREET,SYLACAUGA,AL,35150,2562495604,600,Talladega,For profit - Corporation,...,36,18.667,0,0,0,0,0,0,"260 WEST WALNUT STREET,SYLACAUGA,AL,35150",2020-11-01
2,015012,HIGHLANDS HEALTH AND REHAB,380 WOODS COVE ROAD,SCOTTSBORO,AL,35768,2562183708,350,Jackson,Government - County,...,44,30.667,0,0,0,0,0,0,"380 WOODS COVE ROAD,SCOTTSBORO,AL,35768",2020-11-01
3,015014,EASTVIEW REHABILITATION & HEALTHCARE CENTER,7755 FOURTH AVENUE SOUTH,BIRMINGHAM,AL,35206,2058330146,360,Jefferson,For profit - Individual,...,24,12.667,0,0,0,0,0,0,"7755 FOURTH AVENUE SOUTH,BIRMINGHAM,AL,35206",2020-11-01
4,015015,PLANTATION MANOR NURSING HOME,6450 OLD TUSCALOOSA HIGHWAY P O BOX 97,MC CALLA,AL,35111,2054776161,360,Jefferson,For profit - Individual,...,16,14.000,0,0,2,29611,0,2,"6450 OLD TUSCALOOSA HIGHWAY P O BOX 97,MC CA...",2020-11-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15343,676485,PRINCETON MEDICAL LODGE,1401 W. PRINCETON DR.,PRINCETON,TX,75407,9727342100,310,Collin,For profit - Corporation,...,.,NaN,0,0,0,0,0,0,"1401 W. PRINCETON DR.,PRINCETON,TX,75407",2020-11-01
15344,676487,THE CENTER AT PARMER,13800 N FM 620 RD SB,AUSTIN,TX,78717,7372366400,970,Williamson,For profit - Limited Liability company,...,.,NaN,0,0,0,0,0,0,"13800 N FM 620 RD SB,AUSTIN,TX,78717",2020-11-01
15345,676488,CEDAR HOLLOW REHABILITATION CENTER,5011 NORTH US HWY 75,SHERMAN,TX,75090,9037712000,564,Grayson,For profit - Corporation,...,.,NaN,0,0,0,0,0,0,"5011 NORTH US HWY 75,SHERMAN,TX,75090",2020-11-01
15346,686123,KENDALL LAKES HEALTH AND REHABILITATION CENTER,5280 SW 157 AVENUE,MIAMI,FL,33185,7864337400,120,Miami-Dade,For profit - Corporation,...,.,NaN,0,0,0,0,0,0,"5280 SW 157 AVENUE,MIAMI,FL,33185",2020-11-01
15347,686124,HARMONY HEALTH CENTER,9820 N KENDALL DRIVE,MIAMI,FL,33176,3052716311,120,Miami-Dade,For profit - Limited Liability company,...,.,NaN,0,0,0,0,0,0,"9820 N KENDALL DRIVE,MIAMI,FL,33176",2020-11-01

In [89]:
filteredProvierInfo_2020 = providerInfo_2020[['federal_provider_number', 'provider_name', 'provider_address',
       'provider_city', 'provider_state', 'provider_zip_code',
       'ownership_type', 'average_number_of_residents_per_day','overall_rating',
       'health_inspection_rating','qm_rating',
       'staffing_rating','adjusted_total_nurse_staffing_hours_per_resident_per_day']]

In [90]:
filteredProvierInfo_2020

,federal_provider_number,provider_name,provider_address,provider_city,provider_state,provider_zip_code,ownership_type,average_number_of_residents_per_day,overall_rating,health_inspection_rating,qm_rating,staffing_rating,adjusted_total_nurse_staffing_hours_per_resident_per_day
0,015009,"BURNS NURSING HOME, INC.",701 MONROE STREET NW,RUSSELLVILLE,AL,35653,For profit - Corporation,44.9,5.0,5.0,5.0,5.0,4.60948
1,015010,COOSA VALLEY HEALTHCARE CENTER,260 WEST WALNUT STREET,SYLACAUGA,AL,35150,For profit - Corporation,76.1,4.0,3.0,4.0,5.0,5.27858
2,015012,HIGHLANDS HEALTH AND REHAB,380 WOODS COVE ROAD,SCOTTSBORO,AL,35768,Government - County,41.0,3.0,2.0,2.0,5.0,5.10482
3,015014,EASTVIEW REHABILITATION & HEALTHCARE CENTER,7755 FOURTH AVENUE SOUTH,BIRMINGHAM,AL,35206,For profit - Individual,79.6,3.0,4.0,1.0,4.0,4.15304
4,015015,PLANTATION MANOR NURSING HOME,6450 OLD TUSCALOOSA HIGHWAY P O BOX 97,MC CALLA,AL,35111,For profit - Individual,84.0,4.0,4.0,2.0,2.0,3.93496
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15343,676485,PRINCETON MEDICAL LODGE,1401 W. PRINCETON DR.,PRINCETON,TX,75407,For profit - Corporation,NaN,NaN,NaN,NaN,NaN,NaN
15344,676487,THE CENTER AT PARMER,13800 N FM 620 RD SB,AUSTIN,TX,78717,For profit - Limited Liability company,NaN,NaN,NaN,NaN,NaN,NaN
15345,676488,CEDAR HOLLOW REHABILITATION CENTER,5011 NORTH US HWY 75,SHERMAN,TX,75090,For profit - Corporation,NaN,NaN,NaN,NaN,NaN,NaN
15346,686123,KENDALL LAKES HEALTH AND REHABILITATION CENTER,5280 SW 157 AVENUE,MIAMI,FL,33185,For profit - Corporation,131.5,NaN,NaN,NaN,NaN,NaN
15347,686124,HARMONY HEALTH CENTER,9820 N KENDALL DRIVE,MIAMI,FL,33176,For profit - Limited Liability company,182.7,NaN,NaN,NaN,NaN,NaN

In [91]:
filteredProvierInfo_2020.rename(columns={
    'federal_provider_number': 'provnum',
    'provider_name': 'provname',
    'provider_address': 'address',
    'provider_city': 'city',
    'provider_state': 'state',
    'provider_zip_code': 'zip',
    'ownership_type': 'ownership',
    'average_number_of_residents_per_day': 'restot',
    'overall_rating': 'overall_rating',
    'health_inspection_rating': 'quality_rating',
    'qm_rating': 'staffing_rating',
    'adjusted_total_nurse_staffing_hours_per_resident_per_day': 'adj_total'
})

,provnum,provname,address,city,state,zip,ownership,restot,overall_rating,quality_rating,staffing_rating,staffing_rating,adj_total
0,015009,"BURNS NURSING HOME, INC.",701 MONROE STREET NW,RUSSELLVILLE,AL,35653,For profit - Corporation,44.9,5.0,5.0,5.0,5.0,4.60948
1,015010,COOSA VALLEY HEALTHCARE CENTER,260 WEST WALNUT STREET,SYLACAUGA,AL,35150,For profit - Corporation,76.1,4.0,3.0,4.0,5.0,5.27858
2,015012,HIGHLANDS HEALTH AND REHAB,380 WOODS COVE ROAD,SCOTTSBORO,AL,35768,Government - County,41.0,3.0,2.0,2.0,5.0,5.10482
3,015014,EASTVIEW REHABILITATION & HEALTHCARE CENTER,7755 FOURTH AVENUE SOUTH,BIRMINGHAM,AL,35206,For profit - Individual,79.6,3.0,4.0,1.0,4.0,4.15304
4,015015,PLANTATION MANOR NURSING HOME,6450 OLD TUSCALOOSA HIGHWAY P O BOX 97,MC CALLA,AL,35111,For profit - Individual,84.0,4.0,4.0,2.0,2.0,3.93496
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15343,676485,PRINCETON MEDICAL LODGE,1401 W. PRINCETON DR.,PRINCETON,TX,75407,For profit - Corporation,NaN,NaN,NaN,NaN,NaN,NaN
15344,676487,THE CENTER AT PARMER,13800 N FM 620 RD SB,AUSTIN,TX,78717,For profit - Limited Liability company,NaN,NaN,NaN,NaN,NaN,NaN
15345,676488,CEDAR HOLLOW REHABILITATION CENTER,5011 NORTH US HWY 75,SHERMAN,TX,75090,For profit - Corporation,NaN,NaN,NaN,NaN,NaN,NaN
15346,686123,KENDALL LAKES HEALTH AND REHABILITATION CENTER,5280 SW 157 AVENUE,MIAMI,FL,33185,For profit - Corporation,131.5,NaN,NaN,NaN,NaN,NaN
15347,686124,HARMONY HEALTH CENTER,9820 N KENDALL DRIVE,MIAMI,FL,33176,For profit - Limited Liability company,182.7,NaN,NaN,NaN,NaN,NaN

In [92]:
filteredProvierInfo_2020

,federal_provider_number,provider_name,provider_address,provider_city,provider_state,provider_zip_code,ownership_type,average_number_of_residents_per_day,overall_rating,health_inspection_rating,qm_rating,staffing_rating,adjusted_total_nurse_staffing_hours_per_resident_per_day
0,015009,"BURNS NURSING HOME, INC.",701 MONROE STREET NW,RUSSELLVILLE,AL,35653,For profit - Corporation,44.9,5.0,5.0,5.0,5.0,4.60948
1,015010,COOSA VALLEY HEALTHCARE CENTER,260 WEST WALNUT STREET,SYLACAUGA,AL,35150,For profit - Corporation,76.1,4.0,3.0,4.0,5.0,5.27858
2,015012,HIGHLANDS HEALTH AND REHAB,380 WOODS COVE ROAD,SCOTTSBORO,AL,35768,Government - County,41.0,3.0,2.0,2.0,5.0,5.10482
3,015014,EASTVIEW REHABILITATION & HEALTHCARE CENTER,7755 FOURTH AVENUE SOUTH,BIRMINGHAM,AL,35206,For profit - Individual,79.6,3.0,4.0,1.0,4.0,4.15304
4,015015,PLANTATION MANOR NURSING HOME,6450 OLD TUSCALOOSA HIGHWAY P O BOX 97,MC CALLA,AL,35111,For profit - Individual,84.0,4.0,4.0,2.0,2.0,3.93496
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15343,676485,PRINCETON MEDICAL LODGE,1401 W. PRINCETON DR.,PRINCETON,TX,75407,For profit - Corporation,NaN,NaN,NaN,NaN,NaN,NaN
15344,676487,THE CENTER AT PARMER,13800 N FM 620 RD SB,AUSTIN,TX,78717,For profit - Limited Liability company,NaN,NaN,NaN,NaN,NaN,NaN
15345,676488,CEDAR HOLLOW REHABILITATION CENTER,5011 NORTH US HWY 75,SHERMAN,TX,75090,For profit - Corporation,NaN,NaN,NaN,NaN,NaN,NaN
15346,686123,KENDALL LAKES HEALTH AND REHABILITATION CENTER,5280 SW 157 AVENUE,MIAMI,FL,33185,For profit - Corporation,131.5,NaN,NaN,NaN,NaN,NaN
15347,686124,HARMONY HEALTH CENTER,9820 N KENDALL DRIVE,MIAMI,FL,33176,For profit - Limited Liability company,182.7,NaN,NaN,NaN,NaN,NaN

In [93]:
filteredProvierInfo_2020.rename(columns={
    'federal_provider_number': 'provnum',
    'provider_name': 'provname',
    'provider_address': 'address',
    'provider_city': 'city',
    'provider_state': 'state',
    'provider_zip_code': 'zip',
    'ownership_type': 'ownership',
    'average_number_of_residents_per_day': 'restot',
    'overall_rating': 'overall_rating',
    'health_inspection_rating': 'quality_rating',
    'qm_rating': 'staffing_rating',
    'adjusted_total_nurse_staffing_hours_per_resident_per_day': 'adj_total'
})

,provnum,provname,address,city,state,zip,ownership,restot,overall_rating,quality_rating,staffing_rating,staffing_rating,adj_total
0,015009,"BURNS NURSING HOME, INC.",701 MONROE STREET NW,RUSSELLVILLE,AL,35653,For profit - Corporation,44.9,5.0,5.0,5.0,5.0,4.60948
1,015010,COOSA VALLEY HEALTHCARE CENTER,260 WEST WALNUT STREET,SYLACAUGA,AL,35150,For profit - Corporation,76.1,4.0,3.0,4.0,5.0,5.27858
2,015012,HIGHLANDS HEALTH AND REHAB,380 WOODS COVE ROAD,SCOTTSBORO,AL,35768,Government - County,41.0,3.0,2.0,2.0,5.0,5.10482
3,015014,EASTVIEW REHABILITATION & HEALTHCARE CENTER,7755 FOURTH AVENUE SOUTH,BIRMINGHAM,AL,35206,For profit - Individual,79.6,3.0,4.0,1.0,4.0,4.15304
4,015015,PLANTATION MANOR NURSING HOME,6450 OLD TUSCALOOSA HIGHWAY P O BOX 97,MC CALLA,AL,35111,For profit - Individual,84.0,4.0,4.0,2.0,2.0,3.93496
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15343,676485,PRINCETON MEDICAL LODGE,1401 W. PRINCETON DR.,PRINCETON,TX,75407,For profit - Corporation,NaN,NaN,NaN,NaN,NaN,NaN
15344,676487,THE CENTER AT PARMER,13800 N FM 620 RD SB,AUSTIN,TX,78717,For profit - Limited Liability company,NaN,NaN,NaN,NaN,NaN,NaN
15345,676488,CEDAR HOLLOW REHABILITATION CENTER,5011 NORTH US HWY 75,SHERMAN,TX,75090,For profit - Corporation,NaN,NaN,NaN,NaN,NaN,NaN
15346,686123,KENDALL LAKES HEALTH AND REHABILITATION CENTER,5280 SW 157 AVENUE,MIAMI,FL,33185,For profit - Corporation,131.5,NaN,NaN,NaN,NaN,NaN
15347,686124,HARMONY HEALTH CENTER,9820 N KENDALL DRIVE,MIAMI,FL,33176,For profit - Limited Liability company,182.7,NaN,NaN,NaN,NaN,NaN

In [94]:
filteredProvierInfo_2020

,federal_provider_number,provider_name,provider_address,provider_city,provider_state,provider_zip_code,ownership_type,average_number_of_residents_per_day,overall_rating,health_inspection_rating,qm_rating,staffing_rating,adjusted_total_nurse_staffing_hours_per_resident_per_day
0,015009,"BURNS NURSING HOME, INC.",701 MONROE STREET NW,RUSSELLVILLE,AL,35653,For profit - Corporation,44.9,5.0,5.0,5.0,5.0,4.60948
1,015010,COOSA VALLEY HEALTHCARE CENTER,260 WEST WALNUT STREET,SYLACAUGA,AL,35150,For profit - Corporation,76.1,4.0,3.0,4.0,5.0,5.27858
2,015012,HIGHLANDS HEALTH AND REHAB,380 WOODS COVE ROAD,SCOTTSBORO,AL,35768,Government - County,41.0,3.0,2.0,2.0,5.0,5.10482
3,015014,EASTVIEW REHABILITATION & HEALTHCARE CENTER,7755 FOURTH AVENUE SOUTH,BIRMINGHAM,AL,35206,For profit - Individual,79.6,3.0,4.0,1.0,4.0,4.15304
4,015015,PLANTATION MANOR NURSING HOME,6450 OLD TUSCALOOSA HIGHWAY P O BOX 97,MC CALLA,AL,35111,For profit - Individual,84.0,4.0,4.0,2.0,2.0,3.93496
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15343,676485,PRINCETON MEDICAL LODGE,1401 W. PRINCETON DR.,PRINCETON,TX,75407,For profit - Corporation,NaN,NaN,NaN,NaN,NaN,NaN
15344,676487,THE CENTER AT PARMER,13800 N FM 620 RD SB,AUSTIN,TX,78717,For profit - Limited Liability company,NaN,NaN,NaN,NaN,NaN,NaN
15345,676488,CEDAR HOLLOW REHABILITATION CENTER,5011 NORTH US HWY 75,SHERMAN,TX,75090,For profit - Corporation,NaN,NaN,NaN,NaN,NaN,NaN
15346,686123,KENDALL LAKES HEALTH AND REHABILITATION CENTER,5280 SW 157 AVENUE,MIAMI,FL,33185,For profit - Corporation,131.5,NaN,NaN,NaN,NaN,NaN
15347,686124,HARMONY HEALTH CENTER,9820 N KENDALL DRIVE,MIAMI,FL,33176,For profit - Limited Liability company,182.7,NaN,NaN,NaN,NaN,NaN

In [95]:
filteredProvierInfo_2020= filteredProvierInfo_2020.rename(columns={
    'federal_provider_number': 'provnum',
    'provider_name': 'provname',
    'provider_address': 'address',
    'provider_city': 'city',
    'provider_state': 'state',
    'provider_zip_code': 'zip',
    'ownership_type': 'ownership',
    'average_number_of_residents_per_day': 'restot',
    'overall_rating': 'overall_rating',
    'health_inspection_rating': 'quality_rating',
    'qm_rating': 'staffing_rating',
    'adjusted_total_nurse_staffing_hours_per_resident_per_day': 'adj_total'
})

In [96]:
filteredProvierInfo_2020

,provnum,provname,address,city,state,zip,ownership,restot,overall_rating,quality_rating,staffing_rating,staffing_rating,adj_total
0,015009,"BURNS NURSING HOME, INC.",701 MONROE STREET NW,RUSSELLVILLE,AL,35653,For profit - Corporation,44.9,5.0,5.0,5.0,5.0,4.60948
1,015010,COOSA VALLEY HEALTHCARE CENTER,260 WEST WALNUT STREET,SYLACAUGA,AL,35150,For profit - Corporation,76.1,4.0,3.0,4.0,5.0,5.27858
2,015012,HIGHLANDS HEALTH AND REHAB,380 WOODS COVE ROAD,SCOTTSBORO,AL,35768,Government - County,41.0,3.0,2.0,2.0,5.0,5.10482
3,015014,EASTVIEW REHABILITATION & HEALTHCARE CENTER,7755 FOURTH AVENUE SOUTH,BIRMINGHAM,AL,35206,For profit - Individual,79.6,3.0,4.0,1.0,4.0,4.15304
4,015015,PLANTATION MANOR NURSING HOME,6450 OLD TUSCALOOSA HIGHWAY P O BOX 97,MC CALLA,AL,35111,For profit - Individual,84.0,4.0,4.0,2.0,2.0,3.93496
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15343,676485,PRINCETON MEDICAL LODGE,1401 W. PRINCETON DR.,PRINCETON,TX,75407,For profit - Corporation,NaN,NaN,NaN,NaN,NaN,NaN
15344,676487,THE CENTER AT PARMER,13800 N FM 620 RD SB,AUSTIN,TX,78717,For profit - Limited Liability company,NaN,NaN,NaN,NaN,NaN,NaN
15345,676488,CEDAR HOLLOW REHABILITATION CENTER,5011 NORTH US HWY 75,SHERMAN,TX,75090,For profit - Corporation,NaN,NaN,NaN,NaN,NaN,NaN
15346,686123,KENDALL LAKES HEALTH AND REHABILITATION CENTER,5280 SW 157 AVENUE,MIAMI,FL,33185,For profit - Corporation,131.5,NaN,NaN,NaN,NaN,NaN
15347,686124,HARMONY HEALTH CENTER,9820 N KENDALL DRIVE,MIAMI,FL,33176,For profit - Limited Liability company,182.7,NaN,NaN,NaN,NaN,NaN

In [97]:
filteredProvierInfo_2020.to_csv("filteredProviderInfo_2020.csv", index=False)

In [98]:
providerInfo_2021 = pd.read_csv(r"/Users/brandonnguyen/Desktop/ACE_Project/ProviderInfo_2021.csv")

In [99]:
filteredProvierInfo_2021 = providerInfo_2021[['federal_provider_number', 'provider_name', 'provider_address',
       'provider_city', 'provider_state', 'provider_zip_code',
       'ownership_type', 'average_number_of_residents_per_day','overall_rating',
       'health_inspection_rating','qm_rating',
       'staffing_rating','adjusted_total_nurse_staffing_hours_per_resident_per_day']]

In [100]:
filteredProvierInfo_2021

,federal_provider_number,provider_name,provider_address,provider_city,provider_state,provider_zip_code,ownership_type,average_number_of_residents_per_day,overall_rating,health_inspection_rating,qm_rating,staffing_rating,adjusted_total_nurse_staffing_hours_per_resident_per_day
0,015009,"BURNS NURSING HOME, INC.",701 MONROE STREET NW,RUSSELLVILLE,AL,35653,For profit - Corporation,53.2,5.0,5.0,5.0,1.0,NaN
1,015010,COOSA VALLEY HEALTHCARE CENTER,260 WEST WALNUT STREET,SYLACAUGA,AL,35150,For profit - Corporation,72.5,4.0,3.0,4.0,5.0,4.98569
2,015012,HIGHLANDS HEALTH AND REHAB,380 WOODS COVE ROAD,SCOTTSBORO,AL,35768,Government - County,40.3,1.0,2.0,3.0,1.0,2.07468
3,015014,EASTVIEW REHABILITATION & HEALTHCARE CENTER,7755 FOURTH AVENUE SOUTH,BIRMINGHAM,AL,35206,For profit - Individual,68.1,3.0,4.0,2.0,1.0,NaN
4,015015,PLANTATION MANOR NURSING HOME,6450 OLD TUSCALOOSA HIGHWAY,MC CALLA,AL,35111,For profit - Individual,75.7,3.0,3.0,3.0,3.0,4.21466
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15259,676498,THE VILLAGE AT INCARNATE WORD,4707 BROADWAY STREET,SAN ANTONIO,TX,78209,Non profit - Other,NaN,NaN,NaN,NaN,NaN,NaN
15260,676499,SPRINGTOWN PARK REHABILITATION AND CARE CENTER,201 WILLIAMS WARD RD.,SPRINGTOWN,TX,76082,For profit - Partnership,NaN,NaN,NaN,NaN,NaN,NaN
15261,686123,KENDALL LAKES HEALTH AND REHABILITATION CENTER,5280 SW 157 AVENUE,MIAMI,FL,33185,For profit - Corporation,144.7,5.0,5.0,5.0,4.0,4.03535
15262,686124,HARMONY HEALTH CENTER,9820 N KENDALL DRIVE,MIAMI,FL,33176,For profit - Corporation,189.9,3.0,2.0,4.0,4.0,4.02809
15263,745001,ESTATES AT SHAVANO PARK,4366 LOCKHILL SELMA,SHAVANO PARK,TX,78249,For profit - Corporation,NaN,NaN,NaN,NaN,NaN,NaN

In [101]:
filteredProvierInfo_2021= filteredProvierInfo_2021.rename(columns={
    'federal_provider_number': 'provnum',
    'provider_name': 'provname',
    'provider_address': 'address',
    'provider_city': 'city',
    'provider_state': 'state',
    'provider_zip_code': 'zip',
    'ownership_type': 'ownership',
    'average_number_of_residents_per_day': 'restot',
    'overall_rating': 'overall_rating',
    'health_inspection_rating': 'quality_rating',
    'qm_rating': 'staffing_rating',
    'adjusted_total_nurse_staffing_hours_per_resident_per_day': 'adj_total'
})

In [102]:
filteredProvierInfo_2021

,provnum,provname,address,city,state,zip,ownership,restot,overall_rating,quality_rating,staffing_rating,staffing_rating,adj_total
0,015009,"BURNS NURSING HOME, INC.",701 MONROE STREET NW,RUSSELLVILLE,AL,35653,For profit - Corporation,53.2,5.0,5.0,5.0,1.0,NaN
1,015010,COOSA VALLEY HEALTHCARE CENTER,260 WEST WALNUT STREET,SYLACAUGA,AL,35150,For profit - Corporation,72.5,4.0,3.0,4.0,5.0,4.98569
2,015012,HIGHLANDS HEALTH AND REHAB,380 WOODS COVE ROAD,SCOTTSBORO,AL,35768,Government - County,40.3,1.0,2.0,3.0,1.0,2.07468
3,015014,EASTVIEW REHABILITATION & HEALTHCARE CENTER,7755 FOURTH AVENUE SOUTH,BIRMINGHAM,AL,35206,For profit - Individual,68.1,3.0,4.0,2.0,1.0,NaN
4,015015,PLANTATION MANOR NURSING HOME,6450 OLD TUSCALOOSA HIGHWAY,MC CALLA,AL,35111,For profit - Individual,75.7,3.0,3.0,3.0,3.0,4.21466
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15259,676498,THE VILLAGE AT INCARNATE WORD,4707 BROADWAY STREET,SAN ANTONIO,TX,78209,Non profit - Other,NaN,NaN,NaN,NaN,NaN,NaN
15260,676499,SPRINGTOWN PARK REHABILITATION AND CARE CENTER,201 WILLIAMS WARD RD.,SPRINGTOWN,TX,76082,For profit - Partnership,NaN,NaN,NaN,NaN,NaN,NaN
15261,686123,KENDALL LAKES HEALTH AND REHABILITATION CENTER,5280 SW 157 AVENUE,MIAMI,FL,33185,For profit - Corporation,144.7,5.0,5.0,5.0,4.0,4.03535
15262,686124,HARMONY HEALTH CENTER,9820 N KENDALL DRIVE,MIAMI,FL,33176,For profit - Corporation,189.9,3.0,2.0,4.0,4.0,4.02809
15263,745001,ESTATES AT SHAVANO PARK,4366 LOCKHILL SELMA,SHAVANO PARK,TX,78249,For profit - Corporation,NaN,NaN,NaN,NaN,NaN,NaN

In [103]:
filteredProvierInfo_2021.to_csv("filteredProviderInfo_2021.csv", index=False)

In [104]:
providerInfo_2015 = pd.read_csv(r"/Users/brandonnguyen/Desktop/ACE_Project/ProviderInfo_2015.csv")

In [105]:
providerInfo_2015

,provnum,PROVNAME,ADDRESS,CITY,STATE,ZIP,PHONE,COUNTY_SSA,COUNTY_NAME,OWNERSHIP,...,CYCLE_3_REVISIT_SCORE,CYCLE_3_TOTAL_SCORE,WEIGHTED_ALL_CYCLES_SCORE,incident_cnt,cmplnt_cnt,FINE_CNT,FINE_TOT,PAYDEN_CNT,TOT_PENLTY_CNT,FILEDATE
0,015009,"BURNS NURSING HOME, INC.",701 MONROE STREET NW,RUSSELLVILLE,AL,35653,2563324110,290,Franklin,For profit - Corporation,...,0,12,15.333,0,0,0,0,0,0,2015-12-01
1,015010,COOSA VALLEY NURSING FACILITY,315 WEST HICKORY STREET,SYLACAUGA,AL,35150,2562495604,600,Talladega,Non profit - Other,...,0,64,53.333,0,2,0,0,0,0,2015-12-01
2,015012,HIGHLANDS HEALTH AND REHAB,380 WOODS COVE ROAD,SCOTTSBORO,AL,35768,2562183708,350,Jackson,Government - County,...,0,24,18.667,0,0,0,0,0,0,2015-12-01
3,015014,EASTVIEW REHABILITATION & HEALTHCARE CENTER,7755 FOURTH AVENUE SOUTH,BIRMINGHAM,AL,35206,2058330146,360,Jefferson,For profit - Corporation,...,0,8,23.333,0,1,0,0,0,0,2015-12-01
4,015015,PLANTATION MANOR NURSING HOME,6450 OLD TUSCALOOSA HIGHWAY P O BOX 97,MC CALLA,AL,35111,2054776161,360,Jefferson,For profit - Corporation,...,0,16,36.667,0,0,0,0,0,0,2015-12-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15656,676384,THE MEDICAL RESORT AT SUGAR LAND,1803 WESCOTT AVENUE,SUGAR LAND,TX,77479,2813294300,530,Fort Bend,For profit - Corporation,...,.,.,.,0,0,0,0,0,0,2015-12-01
15657,676385,CROSSROADS NURSING & REHABILITATION,611 ROSE MARIE BLVD,HEARNE,TX,77859,9792800440,878,Robertson,For profit - Individual,...,.,.,.,0,0,0,0,0,0,2015-12-01
15658,676386,WEST REST HAVEN INC,503 MEADOW DRIVE,WEST,TX,76691,2548265354,780,Mc Lennan,For profit - Corporation,...,.,.,.,0,0,0,0,0,0,2015-12-01
15659,676387,HIGHLAND MEADOWS HEALTH & REHAB,1870 S JOHN KING BLVD,ROCKWALL,TX,75032,9727227408,879,Rockwall,For profit - Individual,...,.,.,.,0,0,0,0,0,0,2015-12-01
15660,676388,THE PAVILION AT CREEKWOOD,2100 CANNON DR,MANSFIELD,TX,76063,8177796500,910,Tarrant,For profit - Corporation,...,.,.,.,0,0,0,0,0,0,2015-12-01

In [107]:
providerInfo_2015.columns = providerInfo_2015.columns.str.lower()

In [108]:
providerInfo_2015

,provnum,provname,address,city,state,zip,phone,county_ssa,county_name,ownership,...,cycle_3_revisit_score,cycle_3_total_score,weighted_all_cycles_score,incident_cnt,cmplnt_cnt,fine_cnt,fine_tot,payden_cnt,tot_penlty_cnt,filedate
0,015009,"BURNS NURSING HOME, INC.",701 MONROE STREET NW,RUSSELLVILLE,AL,35653,2563324110,290,Franklin,For profit - Corporation,...,0,12,15.333,0,0,0,0,0,0,2015-12-01
1,015010,COOSA VALLEY NURSING FACILITY,315 WEST HICKORY STREET,SYLACAUGA,AL,35150,2562495604,600,Talladega,Non profit - Other,...,0,64,53.333,0,2,0,0,0,0,2015-12-01
2,015012,HIGHLANDS HEALTH AND REHAB,380 WOODS COVE ROAD,SCOTTSBORO,AL,35768,2562183708,350,Jackson,Government - County,...,0,24,18.667,0,0,0,0,0,0,2015-12-01
3,015014,EASTVIEW REHABILITATION & HEALTHCARE CENTER,7755 FOURTH AVENUE SOUTH,BIRMINGHAM,AL,35206,2058330146,360,Jefferson,For profit - Corporation,...,0,8,23.333,0,1,0,0,0,0,2015-12-01
4,015015,PLANTATION MANOR NURSING HOME,6450 OLD TUSCALOOSA HIGHWAY P O BOX 97,MC CALLA,AL,35111,2054776161,360,Jefferson,For profit - Corporation,...,0,16,36.667,0,0,0,0,0,0,2015-12-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15656,676384,THE MEDICAL RESORT AT SUGAR LAND,1803 WESCOTT AVENUE,SUGAR LAND,TX,77479,2813294300,530,Fort Bend,For profit - Corporation,...,.,.,.,0,0,0,0,0,0,2015-12-01
15657,676385,CROSSROADS NURSING & REHABILITATION,611 ROSE MARIE BLVD,HEARNE,TX,77859,9792800440,878,Robertson,For profit - Individual,...,.,.,.,0,0,0,0,0,0,2015-12-01
15658,676386,WEST REST HAVEN INC,503 MEADOW DRIVE,WEST,TX,76691,2548265354,780,Mc Lennan,For profit - Corporation,...,.,.,.,0,0,0,0,0,0,2015-12-01
15659,676387,HIGHLAND MEADOWS HEALTH & REHAB,1870 S JOHN KING BLVD,ROCKWALL,TX,75032,9727227408,879,Rockwall,For profit - Individual,...,.,.,.,0,0,0,0,0,0,2015-12-01
15660,676388,THE PAVILION AT CREEKWOOD,2100 CANNON DR,MANSFIELD,TX,76063,8177796500,910,Tarrant,For profit - Corporation,...,.,.,.,0,0,0,0,0,0,2015-12-01

In [109]:
filteredProvierInfo_2015 = providerInfo_2015[['provnum', 'provname', 'address', 'city', 'state', 'zip','ownership','restot',
       'overall_rating','survey_rating','quality_rating',
       'staffing_rating','adj_total' ]]

In [110]:
filteredProvierInfo_2015

,provnum,provname,address,city,state,zip,ownership,restot,overall_rating,survey_rating,quality_rating,staffing_rating,adj_total
0,015009,"BURNS NURSING HOME, INC.",701 MONROE STREET NW,RUSSELLVILLE,AL,35653,For profit - Corporation,52,4.0,4.0,3.0,4.0,3.86798
1,015010,COOSA VALLEY NURSING FACILITY,315 WEST HICKORY STREET,SYLACAUGA,AL,35150,Non profit - Other,79,2.0,1.0,3.0,5.0,5.23164
2,015012,HIGHLANDS HEALTH AND REHAB,380 WOODS COVE ROAD,SCOTTSBORO,AL,35768,Government - County,48,4.0,4.0,2.0,4.0,4.52506
3,015014,EASTVIEW REHABILITATION & HEALTHCARE CENTER,7755 FOURTH AVENUE SOUTH,BIRMINGHAM,AL,35206,For profit - Corporation,84,4.0,3.0,4.0,5.0,4.78249
4,015015,PLANTATION MANOR NURSING HOME,6450 OLD TUSCALOOSA HIGHWAY P O BOX 97,MC CALLA,AL,35111,For profit - Corporation,91,3.0,2.0,2.0,4.0,4.44990
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15656,676384,THE MEDICAL RESORT AT SUGAR LAND,1803 WESCOTT AVENUE,SUGAR LAND,TX,77479,For profit - Corporation,3,NaN,NaN,NaN,NaN,NaN
15657,676385,CROSSROADS NURSING & REHABILITATION,611 ROSE MARIE BLVD,HEARNE,TX,77859,For profit - Individual,3,NaN,NaN,NaN,NaN,NaN
15658,676386,WEST REST HAVEN INC,503 MEADOW DRIVE,WEST,TX,76691,For profit - Corporation,3,NaN,NaN,NaN,NaN,NaN
15659,676387,HIGHLAND MEADOWS HEALTH & REHAB,1870 S JOHN KING BLVD,ROCKWALL,TX,75032,For profit - Individual,3,NaN,NaN,NaN,NaN,NaN
15660,676388,THE PAVILION AT CREEKWOOD,2100 CANNON DR,MANSFIELD,TX,76063,For profit - Corporation,3,NaN,NaN,NaN,NaN,NaN

In [111]:
filteredProvierInfo_2015.to_csv("filteredProviderInfo_2015.csv", index=False)

In [113]:
filteredProvierInfo_2015

,provnum,provname,address,city,state,zip,ownership,restot,overall_rating,survey_rating,quality_rating,staffing_rating,adj_total
0,015009,"BURNS NURSING HOME, INC.",701 MONROE STREET NW,RUSSELLVILLE,AL,35653,For profit - Corporation,52,4.0,4.0,3.0,4.0,3.86798
1,015010,COOSA VALLEY NURSING FACILITY,315 WEST HICKORY STREET,SYLACAUGA,AL,35150,Non profit - Other,79,2.0,1.0,3.0,5.0,5.23164
2,015012,HIGHLANDS HEALTH AND REHAB,380 WOODS COVE ROAD,SCOTTSBORO,AL,35768,Government - County,48,4.0,4.0,2.0,4.0,4.52506
3,015014,EASTVIEW REHABILITATION & HEALTHCARE CENTER,7755 FOURTH AVENUE SOUTH,BIRMINGHAM,AL,35206,For profit - Corporation,84,4.0,3.0,4.0,5.0,4.78249
4,015015,PLANTATION MANOR NURSING HOME,6450 OLD TUSCALOOSA HIGHWAY P O BOX 97,MC CALLA,AL,35111,For profit - Corporation,91,3.0,2.0,2.0,4.0,4.44990
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15656,676384,THE MEDICAL RESORT AT SUGAR LAND,1803 WESCOTT AVENUE,SUGAR LAND,TX,77479,For profit - Corporation,3,NaN,NaN,NaN,NaN,NaN
15657,676385,CROSSROADS NURSING & REHABILITATION,611 ROSE MARIE BLVD,HEARNE,TX,77859,For profit - Individual,3,NaN,NaN,NaN,NaN,NaN
15658,676386,WEST REST HAVEN INC,503 MEADOW DRIVE,WEST,TX,76691,For profit - Corporation,3,NaN,NaN,NaN,NaN,NaN
15659,676387,HIGHLAND MEADOWS HEALTH & REHAB,1870 S JOHN KING BLVD,ROCKWALL,TX,75032,For profit - Individual,3,NaN,NaN,NaN,NaN,NaN
15660,676388,THE PAVILION AT CREEKWOOD,2100 CANNON DR,MANSFIELD,TX,76063,For profit - Corporation,3,NaN,NaN,NaN,NaN,NaN

# Merging Provider_Info

In [164]:
# Adding a year column
filteredProvierInfo_2015['year'] = 2015  
filteredProvierInfo_2016['year'] = 2016  
filteredProvierInfo_2017['year'] = 2017  
filteredProvierInfo_2018['year'] = 2018  
filteredProvierInfo_2019['year'] = 2019  
filteredProvierInfo_2020['year'] = 2020  
filteredProvierInfo_2021['year'] = 2021

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

/var/folders/7t/7qf1whc969jcpbccjdpbv57r0000gn/T/ipykernel_4460/1546310211.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filteredProvierInfo_2015['year'] = 2015
/var/folders/7t/7qf1whc969jcpbccjdpbv57r0000gn/T/ipykernel_4460/1546310211.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filteredProvierInfo_2016['year'] = 2016
/var/folders/7t/7qf1whc969jcpbccjdpbv57r0000gn/T/ipykernel_4460/1546310211.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filteredProvierInfo_2017['year'] = 2017
/var/folders/7t/7qf1whc969jcpbccjdpbv57r0000gn/T/ipykernel_4460/1546310211.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filteredProvierInfo_2018['year'] = 2018
/var/folders/7t/7qf1whc969jcpbccjdpbv57r0000gn/T/ipykernel_4460/1546310211.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filteredProvierInfo_2019['year'] = 2019

In [115]:
filteredProvierInfo_2015

,provnum,provname,address,city,state,zip,ownership,restot,overall_rating,survey_rating,quality_rating,staffing_rating,adj_total,year
0,015009,"BURNS NURSING HOME, INC.",701 MONROE STREET NW,RUSSELLVILLE,AL,35653,For profit - Corporation,52,4.0,4.0,3.0,4.0,3.86798,2015
1,015010,COOSA VALLEY NURSING FACILITY,315 WEST HICKORY STREET,SYLACAUGA,AL,35150,Non profit - Other,79,2.0,1.0,3.0,5.0,5.23164,2015
2,015012,HIGHLANDS HEALTH AND REHAB,380 WOODS COVE ROAD,SCOTTSBORO,AL,35768,Government - County,48,4.0,4.0,2.0,4.0,4.52506,2015
3,015014,EASTVIEW REHABILITATION & HEALTHCARE CENTER,7755 FOURTH AVENUE SOUTH,BIRMINGHAM,AL,35206,For profit - Corporation,84,4.0,3.0,4.0,5.0,4.78249,2015
4,015015,PLANTATION MANOR NURSING HOME,6450 OLD TUSCALOOSA HIGHWAY P O BOX 97,MC CALLA,AL,35111,For profit - Corporation,91,3.0,2.0,2.0,4.0,4.44990,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15656,676384,THE MEDICAL RESORT AT SUGAR LAND,1803 WESCOTT AVENUE,SUGAR LAND,TX,77479,For profit - Corporation,3,NaN,NaN,NaN,NaN,NaN,2015
15657,676385,CROSSROADS NURSING & REHABILITATION,611 ROSE MARIE BLVD,HEARNE,TX,77859,For profit - Individual,3,NaN,NaN,NaN,NaN,NaN,2015
15658,676386,WEST REST HAVEN INC,503 MEADOW DRIVE,WEST,TX,76691,For profit - Corporation,3,NaN,NaN,NaN,NaN,NaN,2015
15659,676387,HIGHLAND MEADOWS HEALTH & REHAB,1870 S JOHN KING BLVD,ROCKWALL,TX,75032,For profit - Individual,3,NaN,NaN,NaN,NaN,NaN,2015
15660,676388,THE PAVILION AT CREEKWOOD,2100 CANNON DR,MANSFIELD,TX,76063,For profit - Corporation,3,NaN,NaN,NaN,NaN,NaN,2015

In [119]:
# Check for columns duplicates
print(filteredProvierInfo_2015.columns.duplicated().any())  
print(filteredProvierInfo_2016.columns.duplicated().any())  
print(filteredProvierInfo_2017.columns.duplicated().any())  
print(filteredProvierInfo_2018.columns.duplicated().any())  
print(filteredProvierInfo_2019.columns.duplicated().any())  
print(filteredProvierInfo_2020.columns.duplicated().any())  
print(filteredProvierInfo_2021.columns.duplicated().any())

False
False
False
False
False
True
True

In [141]:
print(filteredProvierInfo_2015.columns.duplicated().any())  
print(filteredProvierInfo_2016.columns.duplicated().any())  
print(filteredProvierInfo_2017.columns.duplicated().any())  
print(filteredProvierInfo_2018.columns.duplicated().any())  
print(filteredProvierInfo_2019.columns.duplicated().any())  
print(filteredProvierInfo_2020.columns.duplicated().any())  
print(filteredProvierInfo_2021.columns.duplicated().any())

False
False
False
False
False
False
False

In [152]:
#Merge the files
ProviderInfo = pd.concat([
    filteredProvierInfo_2015, filteredProvierInfo_2016, filteredProvierInfo_2017,
    filteredProvierInfo_2018, filteredProvierInfo_2019, filteredProvierInfo_2020,
    filteredProvierInfo_2021
], ignore_index=True)

In [154]:
ProviderInfo.to_csv("ProviderInfo.csv",index=False)

# Merging Cost Report

In [155]:
filteredCostReport_2015['year'] = 2015  
filteredCostReport_2016['year'] = 2016  
filteredCostReport_2017['year'] = 2017  
filteredCostReport_2018['year'] = 2018  
filteredCostReport_2019['year'] = 2019  
filteredCostReport_2020['year'] = 2020  
filteredCostReport_2021['year'] = 2021

/var/folders/7t/7qf1whc969jcpbccjdpbv57r0000gn/T/ipykernel_4460/2966097467.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filteredCostReport_2015['year'] = 2015
/var/folders/7t/7qf1whc969jcpbccjdpbv57r0000gn/T/ipykernel_4460/2966097467.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filteredCostReport_2016['year'] = 2016
/var/folders/7t/7qf1whc969jcpbccjdpbv57r0000gn/T/ipykernel_4460/2966097467.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filteredCostReport_2017['year'] = 2017
/var/folders/7t/7qf1whc969jcpbccjdpbv57r0000gn/T/ipykernel_4460/2966097467.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filteredCostReport_2018['year'] = 2018
/var/folders/7t/7qf1whc969jcpbccjdpbv57r0000gn/T/ipykernel_4460/2966097467.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filteredCostReport_2019['year'] = 2019

In [156]:
filteredCostReport_2015

,rpt_rec_num,provider_ccn,rural_versus_urban,gross_revenue,inpatient_revenue,net_income,net_income_from_patients,net_patient_revenue,number_of_beds,total_bed_days_available,total_costs,total_income,year
0,1089712,495134,U,1800296.0,1800296.0,311430.0,311308.0,1520630.0,120.0,7320.0,211585.0,311431.0,2015
1,1091410,75417,U,2843541.0,2843541.0,-588469.0,-588476.0,2416825.0,114.0,8550.0,207903.0,-588469.0,2015
2,1093283,165252,R,613243.0,613243.0,-47859.0,-39135.0,600033.0,60.0,5520.0,22920.0,-30743.0,2015
3,1095547,225497,U,1935277.0,1935277.0,-63638.0,-66306.0,1378163.0,141.0,8601.0,158386.0,-63638.0,2015
4,1095966,265161,U,818175.0,818175.0,-1613.0,-6087.0,769155.0,172.0,5332.0,56556.0,-1613.0,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15397,1310508,555352,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015
15398,1317431,45357,U,8371129.0,8371129.0,-67387.0,-69923.0,8707761.0,120.0,43800.0,1336487.0,-67387.0,2015
15399,1334160,55728,U,9132853.0,9132853.0,254508.0,143887.0,7642138.0,99.0,36135.0,1250099.0,254508.0,2015
15400,1338020,395735,U,17262402.0,17262402.0,97893.0,-162366.0,11844641.0,140.0,51240.0,2327325.0,97893.0,2015
15401,1345592,275122,R,4803468.0,4803468.0,-206640.0,-208377.0,4168276.0,103.0,37595.0,624773.0,-206640.0,2015

In [157]:
print(filteredCostReport_2015.columns.duplicated().any())  
print(filteredCostReport_2016.columns.duplicated().any())  
print(filteredCostReport_2017.columns.duplicated().any())  
print(filteredCostReport_2018.columns.duplicated().any())  
print(filteredCostReport_2019.columns.duplicated().any())  
print(filteredCostReport_2020.columns.duplicated().any())  
print(filteredCostReport_2021.columns.duplicated().any())

False
False
False
False
False
False
False

In [160]:
CostReport = pd.concat ([
    filteredCostReport_2015, filteredCostReport_2016, filteredCostReport_2017,
    filteredCostReport_2018, filteredCostReport_2019, filteredCostReport_2020,
    filteredCostReport_2021
], ignore_index=True)

In [161]:
CostReport

,rpt_rec_num,provider_ccn,rural_versus_urban,gross_revenue,inpatient_revenue,net_income,net_income_from_patients,net_patient_revenue,number_of_beds,total_bed_days_available,total_costs,total_income,year
0,1089712,495134,U,1800296.0,1800296.0,311430.0,311308.0,1520630.0,120.0,7320.0,211585.0,311431.0,2015
1,1091410,75417,U,2843541.0,2843541.0,-588469.0,-588476.0,2416825.0,114.0,8550.0,207903.0,-588469.0,2015
2,1093283,165252,R,613243.0,613243.0,-47859.0,-39135.0,600033.0,60.0,5520.0,22920.0,-30743.0,2015
3,1095547,225497,U,1935277.0,1935277.0,-63638.0,-66306.0,1378163.0,141.0,8601.0,158386.0,-63638.0,2015
4,1095966,265161,U,818175.0,818175.0,-1613.0,-6087.0,769155.0,172.0,5332.0,56556.0,-1613.0,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...
106264,1365869,505453,U,9351892.0,9351892.0,-959762.0,-1088771.0,8661500.0,100.0,36500.0,357017.0,-959762.0,2021
106265,1365888,675765,U,14843070.0,14843070.0,-840502.0,-2103698.0,12808233.0,388.0,141620.0,2312210.0,-840502.0,2021
106266,1365889,675932,U,9009085.0,8599523.0,1916693.0,1391159.0,7477706.0,126.0,45990.0,1111339.0,1916693.0,2021
106267,1365890,675956,U,12738362.0,12738362.0,1188367.0,-2549765.0,12738362.0,206.0,75190.0,1250246.0,1188367.0,2021
106268,1365892,676481,R,9991720.0,9991720.0,739852.0,454984.0,9991720.0,130.0,47450.0,1493029.0,739852.0,2021

In [162]:
  filteredCostReport_2015

,rpt_rec_num,provider_ccn,rural_versus_urban,gross_revenue,inpatient_revenue,net_income,net_income_from_patients,net_patient_revenue,number_of_beds,total_bed_days_available,total_costs,total_income,year
0,1089712,495134,U,1800296.0,1800296.0,311430.0,311308.0,1520630.0,120.0,7320.0,211585.0,311431.0,2015
1,1091410,75417,U,2843541.0,2843541.0,-588469.0,-588476.0,2416825.0,114.0,8550.0,207903.0,-588469.0,2015
2,1093283,165252,R,613243.0,613243.0,-47859.0,-39135.0,600033.0,60.0,5520.0,22920.0,-30743.0,2015
3,1095547,225497,U,1935277.0,1935277.0,-63638.0,-66306.0,1378163.0,141.0,8601.0,158386.0,-63638.0,2015
4,1095966,265161,U,818175.0,818175.0,-1613.0,-6087.0,769155.0,172.0,5332.0,56556.0,-1613.0,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15397,1310508,555352,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015
15398,1317431,45357,U,8371129.0,8371129.0,-67387.0,-69923.0,8707761.0,120.0,43800.0,1336487.0,-67387.0,2015
15399,1334160,55728,U,9132853.0,9132853.0,254508.0,143887.0,7642138.0,99.0,36135.0,1250099.0,254508.0,2015
15400,1338020,395735,U,17262402.0,17262402.0,97893.0,-162366.0,11844641.0,140.0,51240.0,2327325.0,97893.0,2015
15401,1345592,275122,R,4803468.0,4803468.0,-206640.0,-208377.0,4168276.0,103.0,37595.0,624773.0,-206640.0,2015

In [163]:
CostReport.to_csv("CostReport.csv",index=False)

# QualityMsr Cleaning

In [188]:
# Load the files
def load_csv(filename):
    try:
        return pd.read_csv(filename, encoding="utf-8", low_memory=False)
    except UnicodeDecodeError:
          return pd.read_csv(filename, encoding="ISO-8859-1",low_memory=False)

# Function to standardize column names
def standardize_columns(df):
    df.columns = df.columns.str.lower().str.replace(' ','_')
    return df

file_paths = [
    "QualityMsrMDS_2015.csv",
    "QualityMsrMDS_2016.csv",
    "QualityMsrMDS_2017.csv",
    "QualityMsrMDS_2018.csv",
    "QualityMsrMDS_2019.csv",
    "QualityMsrMDS_2020.csv",
    "QualityMsrMDS_2021.csv",
]

quality_dfs = {}

for file in file_paths:
    year = file.split("_")[-1].split(".")[0] # Extract the year 
    df = load_csv(file)
    df = standardize_columns(df)
    quality_dfs[f"QualityMsrMDS_{year}"] = df

print(quality_dfs["QualityMsrMDS_2020"].head())

  federal_provider_number             provider_name      provider_address  \
0                  015009  BURNS NURSING HOME, INC.  701 MONROE STREET NW
1                  015009  BURNS NURSING HOME, INC.  701 MONROE STREET NW
2                  015009  BURNS NURSING HOME, INC.  701 MONROE STREET NW
3                  015009  BURNS NURSING HOME, INC.  701 MONROE STREET NW
4                  015009  BURNS NURSING HOME, INC.  701 MONROE STREET NW

  provider_city provider_state  provider_zip_code  measure_code  \
0  RUSSELLVILLE             AL              35653           401
1  RUSSELLVILLE             AL              35653           404
2  RUSSELLVILLE             AL              35653           405
3  RUSSELLVILLE             AL              35653           406
4  RUSSELLVILLE             AL              35653           407

                                 measure_description resident_type  \
0  Percentage of long-stay residents whose need f...     Long Stay
1  Percentage of long-stay residents who lose too...     Long Stay
2  Percentage of low risk long-stay residents who...     Long Stay
3  Percentage of long-stay residents with a cathe...     Long Stay
4  Percentage of long-stay residents with a urina...     Long Stay

   q1_measure_score  ...  q3_measure_score  footnote_for_q3_measure_score  \
0           8.33333  ...         16.216220                            NaN
1           6.97674  ...          2.500000                            NaN
2               NaN  ...               NaN                            9.0
3           0.00000  ...          1.754017                            NaN
4           8.33333  ...          0.000000                            NaN

   q4_measure_score  footnote_for_q4_measure_score  \
0         25.000000                            NaN
1          2.777780                            NaN
2               NaN                            9.0
3          2.896903                            NaN
4          0.000000                            NaN

   four_quarter_average_score  footnote_for_four_quarter_average_score  \
0                   14.189190                                      NaN
1                    4.402515                                      NaN
2                   29.310345                                      NaN
3                    1.122400                                      NaN
4                    2.717391                                      NaN

   used_in_quality_measure_five_star_rating  measure_period  \
0                                         Y   2019Q1-2019Q4
1                                         N   2019Q1-2019Q4
2                                         N   2019Q1-2019Q4
3                                         Y   2019Q1-2019Q4
4                                         Y   2019Q1-2019Q4

                                        location processing_date
0  701 MONROE STREET NW, RUSSELLVILLE, AL, 35653      2020-11-01
1  701 MONROE STREET NW, RUSSELLVILLE, AL, 35653      2020-11-01
2  701 MONROE STREET NW, RUSSELLVILLE, AL, 35653      2020-11-01
3  701 MONROE STREET NW, RUSSELLVILLE, AL, 35653      2020-11-01
4  701 MONROE STREET NW, RUSSELLVILLE, AL, 35653      2020-11-01

[5 rows x 23 columns]

In [190]:
# Rename the column names in 2020 and 2021
column_mapping = { 
    'federal_provider_number': 'provnum',
    'measure_code': 'msr_cd',
    'measure_description': 'msr_descr',
    'resident_type': 'stay_type',
    'four_quarter_average_score': 'measure_score_4qtr_avg',
    'used_in_quality_measure_five_star_rating': 'five_star_msr'
}

quality_dfs["QualityMsrMDS_2020"] = quality_dfs["QualityMsrMDS_2020"].rename(columns=column_mapping)
quality_dfs["QualityMsrMDS_2021"] = quality_dfs["QualityMsrMDS_2021"].rename(columns=column_mapping)
print(quality_dfs["QualityMsrMDS_2020"].head(5))
print(quality_dfs["QualityMsrMDS_2021"].head(5))

  provnum             provider_name      provider_address provider_city  \
0  015009  BURNS NURSING HOME, INC.  701 MONROE STREET NW  RUSSELLVILLE
1  015009  BURNS NURSING HOME, INC.  701 MONROE STREET NW  RUSSELLVILLE
2  015009  BURNS NURSING HOME, INC.  701 MONROE STREET NW  RUSSELLVILLE
3  015009  BURNS NURSING HOME, INC.  701 MONROE STREET NW  RUSSELLVILLE
4  015009  BURNS NURSING HOME, INC.  701 MONROE STREET NW  RUSSELLVILLE

  provider_state  provider_zip_code  msr_cd  \
0             AL              35653     401
1             AL              35653     404
2             AL              35653     405
3             AL              35653     406
4             AL              35653     407

                                           msr_descr  stay_type  \
0  Percentage of long-stay residents whose need f...  Long Stay
1  Percentage of long-stay residents who lose too...  Long Stay
2  Percentage of low risk long-stay residents who...  Long Stay
3  Percentage of long-stay residents with a cathe...  Long Stay
4  Percentage of long-stay residents with a urina...  Long Stay

   q1_measure_score  ...  q3_measure_score  footnote_for_q3_measure_score  \
0           8.33333  ...         16.216220                            NaN
1           6.97674  ...          2.500000                            NaN
2               NaN  ...               NaN                            9.0
3           0.00000  ...          1.754017                            NaN
4           8.33333  ...          0.000000                            NaN

   q4_measure_score  footnote_for_q4_measure_score  measure_score_4qtr_avg  \
0         25.000000                            NaN               14.189190
1          2.777780                            NaN                4.402515
2               NaN                            9.0               29.310345
3          2.896903                            NaN                1.122400
4          0.000000                            NaN                2.717391

   footnote_for_four_quarter_average_score  five_star_msr  measure_period  \
0                                      NaN              Y   2019Q1-2019Q4
1                                      NaN              N   2019Q1-2019Q4
2                                      NaN              N   2019Q1-2019Q4
3                                      NaN              Y   2019Q1-2019Q4
4                                      NaN              Y   2019Q1-2019Q4

                                        location processing_date
0  701 MONROE STREET NW, RUSSELLVILLE, AL, 35653      2020-11-01
1  701 MONROE STREET NW, RUSSELLVILLE, AL, 35653      2020-11-01
2  701 MONROE STREET NW, RUSSELLVILLE, AL, 35653      2020-11-01
3  701 MONROE STREET NW, RUSSELLVILLE, AL, 35653      2020-11-01
4  701 MONROE STREET NW, RUSSELLVILLE, AL, 35653      2020-11-01

[5 rows x 23 columns]
  provnum             provider_name      provider_address provider_city  \
0  015009  BURNS NURSING HOME, INC.  701 MONROE STREET NW  RUSSELLVILLE
1  015009  BURNS NURSING HOME, INC.  701 MONROE STREET NW  RUSSELLVILLE
2  015009  BURNS NURSING HOME, INC.  701 MONROE STREET NW  RUSSELLVILLE
3  015009  BURNS NURSING HOME, INC.  701 MONROE STREET NW  RUSSELLVILLE
4  015009  BURNS NURSING HOME, INC.  701 MONROE STREET NW  RUSSELLVILLE

  provider_state  provider_zip_code  msr_cd  \
0             AL              35653     401
1             AL              35653     404
2             AL              35653     405
3             AL              35653     406
4             AL              35653     407

                                           msr_descr  stay_type  \
0  Percentage of long-stay residents whose need f...  Long Stay
1  Percentage of long-stay residents who lose too...  Long Stay
2  Percentage of low risk long-stay residents who...  Long Stay
3  Percentage of long-stay residents with a cathe...  Long Stay
4  Percentage of long-stay residents with a urina...  Long Stay

   q1_measure_score  ...  q3_measure_score  footnote_for_q3_measure_score  \
0          7.894740  ...         15.000000                            NaN
1         12.500000  ...          9.090910                            NaN
2               NaN  ...               NaN                            9.0
3          1.374846  ...          1.604244                            NaN
4          0.000000  ...          0.000000                            NaN

   q4_measure_score  footnote_for_q4_measure_score  measure_score_4qtr_avg  \
0          18.18182                            NaN               15.060243
1           4.54545                            NaN                7.602338
2               NaN                            9.0               66.000001
3           0.00000                            NaN                0.738709
4           0.00000                            NaN                0.555555

   footnote_for_four_quarter_average_score  five_star_msr  measure_period  \
0                                      NaN              Y   2020Q3-2021Q2
1                                      NaN              N   2020Q3-2021Q2
2                                      NaN              N   2020Q3-2021Q2
3                                      NaN              Y   2020Q3-2021Q2
4                                      NaN              Y   2020Q3-2021Q2

                                        location processing_date
0  701 MONROE STREET NW, RUSSELLVILLE, AL, 35653      2021-11-01
1  701 MONROE STREET NW, RUSSELLVILLE, AL, 35653      2021-11-01
2  701 MONROE STREET NW, RUSSELLVILLE, AL, 35653      2021-11-01
3  701 MONROE STREET NW, RUSSELLVILLE, AL, 35653      2021-11-01
4  701 MONROE STREET NW, RUSSELLVILLE, AL, 35653      2021-11-01

[5 rows x 23 columns]

In [198]:
# Filtering out the chosen columns
chosen_columns = [
    'provnum', "msr_cd", 'msr_descr', 'stay_type', 
    'measure_score_4qtr_avg', 'five_star_msr'
]

filtered_quality_dfs = {}

for year in range(2015, 2022):
    year_key = f"QualityMsrMDS_{year}"

    if year_key in quality_dfs:
        filtered_quality_dfs[year_key] = quality_dfs[year_key][chosen_columns]
print(filtered_quality_dfs["QualityMsrMDS_2020"].head())

  provnum  msr_cd                                          msr_descr  \
0  015009     401  Percentage of long-stay residents whose need f...
1  015009     404  Percentage of long-stay residents who lose too...
2  015009     405  Percentage of low risk long-stay residents who...
3  015009     406  Percentage of long-stay residents with a cathe...
4  015009     407  Percentage of long-stay residents with a urina...

   stay_type  measure_score_4qtr_avg five_star_msr
0  Long Stay               14.189190             Y
1  Long Stay                4.402515             N
2  Long Stay               29.310345             N
3  Long Stay                1.122400             Y
4  Long Stay                2.717391             Y

In [204]:
#Adding a year column
for year_key, df in filtered_quality_dfs.items():
    year = int(year_key.split('_')[-1])  # Get the year from the key
    df['year'] = year  
for year_key, df in filtered_quality_dfs.items():
    print(f"Displaying DataFrame for {year_key}:")
    display(df.head(3))

Displaying DataFrame for QualityMsrMDS_2015:

/var/folders/7t/7qf1whc969jcpbccjdpbv57r0000gn/T/ipykernel_4460/566998201.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['year'] = year

,provnum,msr_cd,msr_descr,stay_type,measure_score_4qtr_avg,five_star_msr,year
0,15009,401,Percent of Long Stay Residents Whose Need for ...,Long Stay,15.596331,Y,2015
1,15009,402,Percent of Long Stay Residents Who Self Report...,Long Stay,11.579101,Y,2015
2,15009,403,Percent of High Risk Long Stay Residents With ...,Long Stay,2.777780,Y,2015

Displaying DataFrame for QualityMsrMDS_2016:

,provnum,msr_cd,msr_descr,stay_type,measure_score_4qtr_avg,five_star_msr,year
0,015009,401,Percentage of long-stay residents whose need f...,Long Stay,9.271522,Y,2016
1,015009,402,Percentage of long-stay residents who self-rep...,Long Stay,16.715407,Y,2016
2,015009,403,Percentage of high risk long-stay residents wi...,Long Stay,1.290322,Y,2016

Displaying DataFrame for QualityMsrMDS_2017:

,provnum,msr_cd,msr_descr,stay_type,measure_score_4qtr_avg,five_star_msr,year
0,015009,401,Percentage of long-stay residents whose need f...,Long Stay,18.493148,Y,2017
1,015009,402,Percentage of long-stay residents who self-rep...,Long Stay,4.367560,Y,2017
2,015009,403,Percentage of high risk long-stay residents wi...,Long Stay,0.613496,Y,2017

Displaying DataFrame for QualityMsrMDS_2018:

,provnum,msr_cd,msr_descr,stay_type,measure_score_4qtr_avg,five_star_msr,year
0,015009,401,Percentage of long-stay residents whose need f...,Long Stay,14.383562,Y,2018
1,015009,402,Percentage of long-stay residents who self-rep...,Long Stay,0.554441,Y,2018
2,015009,403,Percentage of high risk long-stay residents wi...,Long Stay,1.162790,Y,2018

Displaying DataFrame for QualityMsrMDS_2019:

,provnum,msr_cd,msr_descr,stay_type,measure_score_4qtr_avg,five_star_msr,year
0,015009,2,Percentage of SNF residents with pressure ulce...,Short Stay,1.760000,Y,2019
1,015009,401,Percentage of long-stay residents whose need f...,Long Stay,9.090909,Y,2019
2,015009,404,Percentage of long-stay residents who lose too...,Long Stay,3.550294,N,2019

Displaying DataFrame for QualityMsrMDS_2020:

,provnum,msr_cd,msr_descr,stay_type,measure_score_4qtr_avg,five_star_msr,year
0,015009,401,Percentage of long-stay residents whose need f...,Long Stay,14.189190,Y,2020
1,015009,404,Percentage of long-stay residents who lose too...,Long Stay,4.402515,N,2020
2,015009,405,Percentage of low risk long-stay residents who...,Long Stay,29.310345,N,2020

Displaying DataFrame for QualityMsrMDS_2021:

,provnum,msr_cd,msr_descr,stay_type,measure_score_4qtr_avg,five_star_msr,year
0,015009,401,Percentage of long-stay residents whose need f...,Long Stay,15.060243,Y,2021
1,015009,404,Percentage of long-stay residents who lose too...,Long Stay,7.602338,N,2021
2,015009,405,Percentage of low risk long-stay residents who...,Long Stay,66.000001,N,2021

In [205]:
#Merging the files
QualityMeasure = pd.concat(filtered_quality_dfs.values(), ignore_index=True)
display(QualityMeasure.head())

,provnum,msr_cd,msr_descr,stay_type,measure_score_4qtr_avg,five_star_msr,year
0,15009,401,Percent of Long Stay Residents Whose Need for ...,Long Stay,15.596331,Y,2015
1,15009,402,Percent of Long Stay Residents Who Self Report...,Long Stay,11.579101,Y,2015
2,15009,403,Percent of High Risk Long Stay Residents With ...,Long Stay,2.777780,Y,2015
3,15009,404,Percent of Long Stay Residents Who Lose Too Mu...,Long Stay,13.740459,N,2015
4,15009,405,Percent of Low Risk Long Stay Residents Who Lo...,Long Stay,30.000000,N,2015